; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _itoa
.extern _printf
.extern _puts
.extern _strlen
.global _main
.extern __sp_base
__zp_scratch = $02

.code
proc _main
    .var _fp = 0
    ; frame: 8 bytes
    phw     #$0000
    phw     #$0000
    phw     #$0000
    phw     #$0000
    ; setup frame pointer
    tsx     
    txa     
    clc     
    adc     #$01
    sta     $FD
    lda     #$01
    adc     #$00
    sta     $FE
    .local _l_buf = 0
; [main.c:82]     char buf[8];
; [main.c:84]     puts("linked hello!");
    lda     $FE
    pha     
    lda     $FD
    pha     
    .var _fp = _fp + 2
    ldax #STR0
    push    .ax
    .var _fp = _fp + 2
    jsr _puts
    sta     $03
    stx     $04
    pla     
    pla     
    pla     
    sta     $FD
    pla     
    sta     $FE
    lda     $03
    ldx     $04
    .var _fp = _fp - 4
; [main.c:86]     itoa(42, buf, 10);
    lda     $FE
    pha     
    lda     $FD
    pha     
    .var _fp = _fp + 2
    ldax #$002A
    push    .ax
    .var _fp = _fp + 2
    ptrstack _l_buf
    push    .ax
    .var _fp = _fp + 2
    ldax #$000A
    push    .ax
    .var _fp = _fp + 2
    jsr _itoa
    sta     $03
    stx     $04
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    sta     $FD
    pla     
    sta     $FE
    lda     $03
    ldx     $04
    .var _fp = _fp - 8
; [main.c:87]     puts(buf);
    lda     $FE
    pha     
    lda     $FD
    pha     
    .var _fp = _fp + 2
    ptrstack _l_buf
    push    .ax
    .var _fp = _fp + 2
    jsr _puts
    sta     $03
    stx     $04
    pla     
    pla     
    pla     
    sta     $FD
    pla     
    sta     $FE
    lda     $03
    ldx     $04
    .var _fp = _fp - 4
; [main.c:89]     printf("string length: %d\n", strlen("hello"));
    lda     $FE
    pha     
    lda     $FD
    pha     
    .var _fp = _fp + 2
    lda     $FE
    pha     
    lda     $FD
    pha     
    .var _fp = _fp + 2
    ldax #STR1
    push    .ax
    .var _fp = _fp + 2
    jsr _strlen
    sta     $03
    stx     $04
    pla     
    pla     
    pla     
    sta     $FD
    pla     
    sta     $FE
    lda     $03
    ldx     $04
    .var _fp = _fp - 4
    push    .ax
    .var _fp = _fp + 2
    ldax #STR2
    push    .ax
    .var _fp = _fp + 2
    jsr _printf
    sta     $03
    stx     $04
    pla     
    pla     
    pla     
    pla     
    pla     
    sta     $FD
    pla     
    sta     $FE
    lda     $03
    ldx     $04
    .var _fp = _fp - 6
; [main.c:91]     puts("done!");
    lda     $FE
    pha     
    lda     $FD
    pha     
    .var _fp = _fp + 2
    ldax #STR3
    push    .ax
    .var _fp = _fp + 2
    jsr _puts
    sta     $03
    stx     $04
    pla     
    pla     
    pla     
    sta     $FD
    pla     
    sta     $FE
    lda     $03
    ldx     $04
    .var _fp = _fp - 4
; [main.c:93]     return 0;
    zero a, x
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    rtn #0
    .func_flags stack_call
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc


.data
; Data Section

.data
STR3:
    .text "done!"
    .byte 0
STR1:
    .text "hello"
    .byte 0
STR0:
    .text "linked hello!"
    .byte 0
STR2:
    .text "string length: %d
"
    .byte 0
