; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _clear_screen
.extern _scroll_line_left
.extern _set_text_color
.extern _strlen
.extern _wait_vsync
.global _draw_banner
.global _init_palette
.global _main
.extern __sp_base

.code
proc _cbm_chrout, B#_p_c
    .var _fp = 0
    .var _p_c = 2
; [main.c:71]     __asm__("lda.sp _p_c");
    lda.sp _p_c
; [main.c:72]     __asm__("jsr $FFD2");
    jsr $FFD2
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_chrin
    .var _fp = 0
; [main.c:77]     __asm__("jsr $FFCF");
    jsr $FFCF
; [main.c:78]     __asm__("ldx #$00");
    ldx #$00
; [main.c:79]     return;
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_getin
    .var _fp = 0
; [main.c:84]     __asm__("jsr $FFE4");
    jsr $FFE4
; [main.c:85]     __asm__("ldx #$00");
    ldx #$00
; [main.c:86]     return;
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_readst
    .var _fp = 0
; [main.c:93]     __asm__("jsr $FFB7");
    jsr $FFB7
; [main.c:94]     __asm__("ldx #$00");
    ldx #$00
; [main.c:95]     return;
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_setlfs, B#_p_lfn, B#_p_device, B#_p_sa
    .var _fp = 0
    .var _p_sa = 2
    .var _p_device = 3
    .var _p_lfn = 4
; [main.c:104]     __asm__("lda.sp _p_sa");
    lda.sp _p_sa
; [main.c:105]     __asm__("tay");
    tay
; [main.c:106]     __asm__("lda.sp _p_device");
    lda.sp _p_device
; [main.c:107]     __asm__("tax");
    tax
; [main.c:108]     __asm__("lda.sp _p_lfn");
    lda.sp _p_lfn
; [main.c:109]     __asm__("jsr $FFBA");
    jsr $FFBA
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_setnam, W#_p_name, B#_p_len
    .var _fp = 0
    .var _p_len = 2
    .var _p_name = 3
; [main.c:116]     __asm__("ldxy _p_name, s");    
    ldxy _p_name, s
; [main.c:117]     __asm__("lda.sp _p_len");
    lda.sp _p_len
; [main.c:118]     __asm__("jsr $FFBD");
    jsr $FFBD
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_open
    .var _fp = 0
; [main.c:125]     __asm__("jsr $FFC0");
    jsr $FFC0
; [main.c:126]     __asm__("lda #$00");
    lda #$00
; [main.c:127]     __asm__("tax");
    tax
; [main.c:128]     __asm__("adc #$00");    
    adc #$00
; [main.c:129]     return;
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_close, B#_p_lfn
    .var _fp = 0
    .var _p_lfn = 2
; [main.c:134]     __asm__("lda.sp _p_lfn");
    lda.sp _p_lfn
; [main.c:135]     __asm__("jsr $FFC3");
    jsr $FFC3
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_chkin, B#_p_lfn
    .var _fp = 0
    .var _p_lfn = 2
; [main.c:140]     __asm__("lda.sp _p_lfn");
    lda.sp _p_lfn
; [main.c:141]     __asm__("tax");
    tax
; [main.c:142]     __asm__("jsr $FFC6");
    jsr $FFC6
; [main.c:143]     __asm__("lda #$00");
    lda #$00
; [main.c:144]     __asm__("tax");
    tax
; [main.c:145]     __asm__("adc #$00");
    adc #$00
; [main.c:146]     return;
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_chkout, B#_p_lfn
    .var _fp = 0
    .var _p_lfn = 2
; [main.c:151]     __asm__("lda.sp _p_lfn");
    lda.sp _p_lfn
; [main.c:152]     __asm__("tax");
    tax
; [main.c:153]     __asm__("jsr $FFC9");
    jsr $FFC9
; [main.c:154]     __asm__("lda #$00");
    lda #$00
; [main.c:155]     __asm__("tax");
    tax
; [main.c:156]     __asm__("adc #$00");
    adc #$00
; [main.c:157]     return;
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_clrchn
    .var _fp = 0
; [main.c:162]     __asm__("jsr $FFCC");
    jsr $FFCC
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_clall
    .var _fp = 0
; [main.c:167]     __asm__("jsr $FFE7");
    jsr $FFE7
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_stop
    .var _fp = 0
; [main.c:174]     __asm__("jsr $FFE1");
    jsr $FFE1
; [main.c:176]     __asm__("php");
    php
; [main.c:177]     __asm__("ldx #$00");
    ldx #$00
; [main.c:178]     __asm__("plp");
    plp
; [main.c:179]     __asm__("bne *+3");     
    bne *+3
; [main.c:180]     __asm__("inx");         
    inx
; [main.c:181]     __asm__("txa");         
    txa
; [main.c:182]     return;
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_gotoxy, B#_p_col, B#_p_row
    .var _fp = 0
    .var _p_row = 2
    .var _p_col = 3
; [main.c:191]     __asm__("clc");
    clc
; [main.c:192]     __asm__("lda.sp _p_row");
    lda.sp _p_row
; [main.c:193]     __asm__("tax");
    tax
; [main.c:194]     __asm__("lda.sp _p_col");
    lda.sp _p_col
; [main.c:195]     __asm__("tay");
    tay
; [main.c:196]     __asm__("jsr $FFF0");
    jsr $FFF0
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_wherexy
    .var _fp = 0
; [main.c:201]     __asm__("sec");
    sec
; [main.c:202]     __asm__("jsr $FFF0");
    jsr $FFF0
; [main.c:204]     __asm__("tya");        
    tya
; [main.c:206]     return;
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_screen
    .var _fp = 0
; [main.c:213]     __asm__("jsr $FFED");
    jsr $FFED
; [main.c:215]     __asm__("txa");        
    txa
; [main.c:216]     __asm__("taz");        
    taz
; [main.c:217]     __asm__("tya");        
    tya
; [main.c:218]     __asm__("tax");        
    tax
; [main.c:219]     __asm__("tza");        
    tza
; [main.c:220]     return;
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_rdtim
    .var _fp = 0
; [main.c:229]     __asm__("jsr $FFDE");
    jsr $FFDE
; [main.c:231]     __asm__("tya");        
    tya
; [main.c:233]     return;
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_listen, B#_p_device
    .var _fp = 0
    .var _p_device = 2
; [main.c:240]     __asm__("lda.sp _p_device");
    lda.sp _p_device
; [main.c:241]     __asm__("jsr $FFB1");
    jsr $FFB1
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_unlisten
    .var _fp = 0
; [main.c:246]     __asm__("jsr $FFAE");
    jsr $FFAE
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_talk, B#_p_device
    .var _fp = 0
    .var _p_device = 2
; [main.c:251]     __asm__("lda.sp _p_device");
    lda.sp _p_device
; [main.c:252]     __asm__("jsr $FFB4");
    jsr $FFB4
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_untalk
    .var _fp = 0
; [main.c:257]     __asm__("jsr $FFAB");
    jsr $FFAB
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_second, B#_p_sa
    .var _fp = 0
    .var _p_sa = 2
; [main.c:262]     __asm__("lda.sp _p_sa");
    lda.sp _p_sa
; [main.c:263]     __asm__("jsr $FF93");
    jsr $FF93
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_tksa, B#_p_sa
    .var _fp = 0
    .var _p_sa = 2
; [main.c:268]     __asm__("lda.sp _p_sa");
    lda.sp _p_sa
; [main.c:269]     __asm__("jsr $FF96");
    jsr $FF96
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_ciout, B#_p_data
    .var _fp = 0
    .var _p_data = 2
; [main.c:274]     __asm__("lda.sp _p_data");
    lda.sp _p_data
; [main.c:275]     __asm__("jsr $FFA8");
    jsr $FFA8
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _cbm_acptr
    .var _fp = 0
; [main.c:280]     __asm__("jsr $FF13");
    jsr $FF13
; [main.c:281]     __asm__("ldx #$00");
    ldx #$00
; [main.c:282]     return;
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

; [main.c:367] const char *message = "    welcome to the mega65!    this scroller was built with cc45 -- a c compiler targeting the 45gs02 cpu.    mixed c and assembly makes hardware access easy.    press run/stop to exit...    ";
; [main.c:369] char palette[7];
; [main.c:370] int palette_len;
.code
proc _init_palette
    .var _fp = 0
; [main.c:373]     palette[0] = 3;
    ldax #$0003
    stax $03
    ptrstack _palette
    stax $05
    zero a, x
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:374]     palette[1] = 14;
    ldax #$000E
    stax $03
    ptrstack _palette
    stax $05
    ldax #$0001
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:375]     palette[2] = 6;
    ldax #$0006
    stax $03
    ptrstack _palette
    stax $05
    ldax #$0002
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:376]     palette[3] = 5;
    ldax #$0005
    stax $03
    ptrstack _palette
    stax $05
    ldax #$0003
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:377]     palette[4] = 13;
    ldax #$000D
    stax $03
    ptrstack _palette
    stax $05
    ldax #$0004
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:378]     palette[5] = 7;
    ldax #$0007
    stax $03
    ptrstack _palette
    stax $05
    ldax #$0005
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:379]     palette[6] = 1;
    ldax #$0001
    stax $03
    ptrstack _palette
    stax $05
    ldax #$0006
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:380]     palette_len = 7;
    stw #$0007, _palette_len
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _draw_banner, B#_p_color
    .var _fp = 0
    ; frame: 4 bytes
    phw     #$0000
    phw     #$0000
    .local _l_scr = 0
    .local _l_i = 2
    .var _p_color = 6
; [main.c:384]     char *scr;
; [main.c:385]     int i;
; [main.c:388]     scr = (char *)0x0800 + 10 * 40;
    stw.sp #$0990, _l_scr
; [main.c:389]     for (i = 0; i < 40; i++)
    stw.sp #$0000, _l_i
L0:
    ldax _l_i, s
    stax $03
    ldax #$0028
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcs @L3
    lda     #$01
    bra     *+4
@L3:
    lda     #$00
@L4:
    ldx     #$00
    cmp #$00
    beq L2
; [main.c:390]         scr[i] = 0x43;    
    ldax #$0043
    stax $03
    ldax _l_scr, s
    stax $05
    ldax _l_i, s
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
L1:
    inw _l_i, s
    bra L0
L2:
; [main.c:393]     scr = (char *)0x0800 + 14 * 40;
    stw.sp #$0A30, _l_scr
; [main.c:394]     for (i = 0; i < 40; i++)
    stw.sp #$0000, _l_i
L5:
    ldax _l_i, s
    stax $03
    ldax #$0028
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcs @L8
    lda     #$01
    bra     *+4
@L8:
    lda     #$00
@L9:
    ldx     #$00
    cmp #$00
    beq L7
; [main.c:395]         scr[i] = 0x43;
    ldax #$0043
    stax $03
    ldax _l_scr, s
    stax $05
    ldax _l_i, s
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
L6:
    inw _l_i, s
    bra L5
L7:
; [main.c:397]     set_text_color(10, color);
    ldax #$000A
    push    .ax
    .var _fp = _fp + 2
    .var _p_color = _p_color + 2
    lda.sp _p_color
    push    a
    .var _fp = _fp + 1
    .var _p_color = _p_color + 1
    jsr _set_text_color
    taz     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 3
    .var _p_color = _p_color - 3
; [main.c:398]     set_text_color(14, color);
    ldax #$000E
    push    .ax
    .var _fp = _fp + 2
    .var _p_color = _p_color + 2
    lda.sp _p_color
    push    a
    .var _fp = _fp + 1
    .var _p_color = _p_color + 1
    jsr _set_text_color
    taz     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 3
    .var _p_color = _p_color - 3
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    rtn #0
    .func_flags stack_call
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _main
    .var _fp = 0
    ; frame: 15 bytes
    phw     #$0000
    phw     #$0000
    phw     #$0000
    phw     #$0000
    phw     #$0000
    phw     #$0000
    phw     #$0000
    lda     #$00
    pha     
    .local _l_msg_pos = 0
    .local _l_msg_len = 2
    .local _l_pal_idx = 4
    .local _l_speed_count = 6
    .local _l_row_ptr = 8
    .local _l_next_char = 10
    .local _l_title = 11
    .local _l_t = 13
; [main.c:402]     int msg_pos;
; [main.c:403]     int msg_len;
; [main.c:404]     int pal_idx;
; [main.c:405]     int speed_count;
; [main.c:406]     char *row_ptr;
; [main.c:407]     char next_char;
; [main.c:409]     clear_screen(1);
    ldax #$0001
    push    a
    .var _fp = _fp + 1
    jsr _clear_screen
    taz     
    pla     
    tza     
    .var _fp = _fp - 1
; [main.c:410]     init_palette();
    jsr _init_palette
; [main.c:412]     (*(char *)0xD020) = 0;     
    zero a, x
    stax $03
    ldax #$D020
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:413]     (*(char *)0xD021) = 0;    
    zero a, x
    stax $03
    ldax #$D021
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:415]     msg_len = strlen(message);
    ldax _message
    push    .ax
    .var _fp = _fp + 2
    jsr _strlen
    taz     
    pla     
    pla     
    tza     
    .var _fp = _fp - 2
    stax _l_msg_len, s
; [main.c:416]     msg_pos = 0;
    stw.sp #$0000, _l_msg_pos
; [main.c:417]     pal_idx = 0;
    stw.sp #$0000, _l_pal_idx
; [main.c:418]     speed_count = 0;
    stw.sp #$0000, _l_speed_count
; [main.c:421]     set_text_color(12, palette[pal_idx]);
    ldax #$000C
    push    .ax
    .var _fp = _fp + 2
    ptrstack _palette
    stax $03
    zero a, x
    add.16 .ax, $03
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    push    a
    .var _fp = _fp + 1
    jsr _set_text_color
    taz     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 3
; [main.c:422]     draw_banner(palette[pal_idx]);
    ptrstack _palette
    stax $03
    zero a, x
    add.16 .ax, $03
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    push    a
    .var _fp = _fp + 1
    jsr _draw_banner
    taz     
    pla     
    tza     
    .var _fp = _fp - 1
; [main.c:425]     cbm_gotoxy(12, 2);
    ldax #$000C
    push    a
    .var _fp = _fp + 1
    ldax #$0002
    push    a
    .var _fp = _fp + 1
    jsr _cbm_gotoxy
    taz     
    pla     
    pla     
    tza     
    .var _fp = _fp - 2
; [main.c:427]         const char *title = "text scroller";
    ldax #STR0
    stax.fp _l_msg_len+9
; [main.c:428]         int t;
; [main.c:429]         for (t = 0; title[t]; t++)
    stw.sp #$0000, _l_t
L10:
    ldax _l_title, s
    stax $03
    ldax _l_t, s
    add.16 .ax, $03
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    cmp #$00
    beq L12
; [main.c:430]             cbm_chrout(title[t]);
    ldax _l_title, s
    stax $03
    ldax _l_t, s
    add.16 .ax, $03
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    push    a
    .var _fp = _fp + 1
    jsr _cbm_chrout
    taz     
    pla     
    tza     
    .var _fp = _fp - 1
L11:
    inw _l_t, s
    bra L10
L12:
; [main.c:434]     while (1) {
L13:
; [main.c:436]         wait_vsync();
    jsr _wait_vsync
; [main.c:439]         if (cbm_stop())
    jsr _cbm_stop
    cmp #$00
    bne @L17
    cpx #$00
    beq L15
@L17:
; [main.c:440]             break;
    bra L14
L15:
; [main.c:443]         scroll_line_left(12);
    ldax #$000C
    push    .ax
    .var _fp = _fp + 2
    jsr _scroll_line_left
    taz     
    pla     
    pla     
    tza     
    .var _fp = _fp - 2
; [main.c:446]         next_char = message[msg_pos];
    ldax _message
    stax $03
    ldax _l_msg_pos, s
    add.16 .ax, $03
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    sta.sp _l_next_char
; [main.c:447]         row_ptr = (char *)0x0800 + 12 * 40;
    stw.sp #$09E0, _l_row_ptr
; [main.c:448]         row_ptr[40 - 1] = next_char;
    lda.sp _l_next_char
    ldx     #$00
    stax $03
    ldax _l_row_ptr, s
    stax $05
    ldax #$0028
    cmp #$00
    bne @L18
    dex
@L18:
    dec     a
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:451]         msg_pos = msg_pos + 1;
    inw _l_msg_pos, s
; [main.c:452]         if (msg_pos >= msg_len)
    ldax _l_msg_pos, s
    stax $03
    ldax _l_msg_len, s
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcc @L21
    lda     #$01
    bra     *+4
@L21:
    lda     #$00
@L22:
    ldx     #$00
    cmp #$00
    beq L19
; [main.c:453]             msg_pos = 0;
    stw.sp #$0000, _l_msg_pos
L19:
; [main.c:456]         if (msg_pos == 0) {
    ldax _l_msg_pos, s
    stax $03
    zero a, x
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bne @L25
    lda     #$01
    bra     *+4
@L25:
    lda     #$00
@L26:
    ldx     #$00
    cmp #$00
    beq L23
; [main.c:457]             pal_idx = pal_idx + 1;
    inw _l_pal_idx, s
; [main.c:458]             if (pal_idx >= palette_len)
    ldax _l_pal_idx, s
    stax $03
    ldax _palette_len
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcc @L29
    lda     #$01
    bra     *+4
@L29:
    lda     #$00
@L30:
    ldx     #$00
    cmp #$00
    beq L27
; [main.c:459]                 pal_idx = 0;
    stw.sp #$0000, _l_pal_idx
L27:
; [main.c:460]             set_text_color(12, palette[pal_idx]);
    ldax #$000C
    push    .ax
    .var _fp = _fp + 2
    ptrstack _palette
    stax $03
    ldax _l_pal_idx, s
    add.16 .ax, $03
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    push    a
    .var _fp = _fp + 1
    jsr _set_text_color
    taz     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 3
; [main.c:461]             draw_banner(palette[pal_idx]);
    ptrstack _palette
    stax $03
    ldax _l_pal_idx, s
    add.16 .ax, $03
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    push    a
    .var _fp = _fp + 1
    jsr _draw_banner
    taz     
    pla     
    tza     
    .var _fp = _fp - 1
; [main.c:462]             (*(char *)0xD020) = palette[pal_idx];
    ptrstack _palette
    stax $03
    ldax _l_pal_idx, s
    add.16 .ax, $03
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    stax $03
    ldax #$D020
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
L23:
    bra L13
L14:
    .func_flags stack_call
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.global _message
.global _palette
.global _palette_len

.data
; Data Section
_message:
    .res 2, 0

.bss
; BSS Section
.global _palette
_palette:
    .res 7
.global _palette_len
_palette_len:
    .res 2

.data
STR0:
    .text "text scroller"
    .byte 0
