; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _test
.global _main

.code
proc _main
    .var _fp = 0
; [main.c:4]     test();
    jsr _test
; [main.c:5]     while (1) {}
L0:
    bra L0
L1:
; [main.c:6]     return 0;
    zero a, x
    rtn #0
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc


.data
; Data Section

.data
