; Generated by cc45
.segmentOrder code, data, bss
.code
.org $2000
    tsx
    stx __saved_spl + 1
    tsy
    sty __saved_sph + 1
    jsr __init
__exit:
__saved_spl:
    ldx #$ff
    txs
__saved_sph:
    ldy #$01
    tys
    rts
__init:
__sp_base = $0101
__zp_scratch = $02
    jsr _init_bss
    jsr _init_features
    jmp _main
_init_features:
    rts
_init_bss:
    rts

.code
proc _error_handler
    .var _fp = 0
; [main.c:4]     print_error();
    jsr _print_error
; [main.c:5]     while(1) {}
L0:
    bra L0
L1:
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _main
    .var _fp = 0
; [main.c:10]     error_handler();
    jsr _error_handler
; [main.c:11]     return 0;
    zero a, x
    rtn #0
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc


.data
; Data Section

.bss
; BSS Section
__bss_start:
__bss_end:

.data
