#include "AssemblerOpcodeDatabase.hpp"
#include <map>

const std::map<std::pair<std::string, AddressingMode>, uint8_t>& AssemblerOpcodeDatabase::getOpcodeMap() {
    static const std::map<std::pair<std::string, AddressingMode>, uint8_t> opcodes = {
        {{"ADC", AddressingMode::BASE_PAGE_INDIRECT_Y}, 0x71},
        {{"ADC", AddressingMode::BASE_PAGE_INDIRECT_Z}, 0x72},
        {{"ADC", AddressingMode::FLAT_INDIRECT_Z}, 0x72},
        {{"ADC", AddressingMode::STACK_RELATIVE}, 0x72},
        {{"ADC", AddressingMode::BASE_PAGE_X_INDIRECT}, 0x61},
        {{"ADC", AddressingMode::ABSOLUTE}, 0x6D},
        {{"ADC", AddressingMode::ABSOLUTE_X}, 0x7D},
        {{"ADC", AddressingMode::ABSOLUTE_Y}, 0x79},
        {{"ADC", AddressingMode::BASE_PAGE}, 0x65},
        {{"ADC", AddressingMode::BASE_PAGE_X}, 0x75},
        {{"ADC", AddressingMode::IMMEDIATE}, 0x69},
        {{"AND", AddressingMode::BASE_PAGE_INDIRECT_Y}, 0x31},
        {{"AND", AddressingMode::BASE_PAGE_INDIRECT_Z}, 0x32},
        {{"AND", AddressingMode::FLAT_INDIRECT_Z}, 0x32},
        {{"AND", AddressingMode::STACK_RELATIVE}, 0x32},
        {{"AND", AddressingMode::BASE_PAGE_X_INDIRECT}, 0x21},
        {{"AND", AddressingMode::ABSOLUTE}, 0x2D},
        {{"AND", AddressingMode::ABSOLUTE_X}, 0x3D},
        {{"AND", AddressingMode::ABSOLUTE_Y}, 0x39},
        {{"AND", AddressingMode::BASE_PAGE}, 0x25},
        {{"AND", AddressingMode::BASE_PAGE_X}, 0x35},
        {{"AND", AddressingMode::IMMEDIATE}, 0x29},
        {{"ASL", AddressingMode::ABSOLUTE}, 0x0E},
        {{"ASL", AddressingMode::ABSOLUTE_X}, 0x1E},
        {{"ASL", AddressingMode::ACCUMULATOR}, 0x0A},
        {{"ASL", AddressingMode::BASE_PAGE}, 0x06},
        {{"ASL", AddressingMode::BASE_PAGE_X}, 0x16},
        {{"ASR", AddressingMode::ACCUMULATOR}, 0x43},
        {{"ASR", AddressingMode::BASE_PAGE}, 0x44},
        {{"ASR", AddressingMode::BASE_PAGE_X}, 0x54},
        {{"ASW", AddressingMode::ABSOLUTE}, 0xCB},
        {{"BBR0", AddressingMode::BASE_PAGE_RELATIVE}, 0x0F},
        {{"BBR1", AddressingMode::BASE_PAGE_RELATIVE}, 0x1F},
        {{"BBR2", AddressingMode::BASE_PAGE_RELATIVE}, 0x2F},
        {{"BBR3", AddressingMode::BASE_PAGE_RELATIVE}, 0x3F},
        {{"BBR4", AddressingMode::BASE_PAGE_RELATIVE}, 0x4F},
        {{"BBR5", AddressingMode::BASE_PAGE_RELATIVE}, 0x5F},
        {{"BBR6", AddressingMode::BASE_PAGE_RELATIVE}, 0x6F},
        {{"BBR7", AddressingMode::BASE_PAGE_RELATIVE}, 0x7F},
        {{"BBS0", AddressingMode::BASE_PAGE_RELATIVE}, 0x8F},
        {{"BBS1", AddressingMode::BASE_PAGE_RELATIVE}, 0x9F},
        {{"BBS2", AddressingMode::BASE_PAGE_RELATIVE}, 0xAF},
        {{"BBS3", AddressingMode::BASE_PAGE_RELATIVE}, 0xBF},
        {{"BBS4", AddressingMode::BASE_PAGE_RELATIVE}, 0xCF},
        {{"BBS5", AddressingMode::BASE_PAGE_RELATIVE}, 0xDF},
        {{"BBS6", AddressingMode::BASE_PAGE_RELATIVE}, 0xEF},
        {{"BBS7", AddressingMode::BASE_PAGE_RELATIVE}, 0xFF},
        {{"BCC", AddressingMode::RELATIVE}, 0x90},
        {{"BCC", AddressingMode::RELATIVE16}, 0x93},
        {{"BCS", AddressingMode::RELATIVE}, 0xB0},
        {{"BCS", AddressingMode::RELATIVE16}, 0xB3},
        {{"BEQ", AddressingMode::RELATIVE}, 0xF0},
        {{"BEQ", AddressingMode::RELATIVE16}, 0xF3},
        {{"BIT", AddressingMode::ABSOLUTE}, 0x2C},
        {{"BIT", AddressingMode::ABSOLUTE_X}, 0x3C},
        {{"BIT", AddressingMode::BASE_PAGE}, 0x24},
        {{"BIT", AddressingMode::BASE_PAGE_X}, 0x34},
        {{"BIT", AddressingMode::IMMEDIATE}, 0x89},
        {{"BMI", AddressingMode::RELATIVE}, 0x30},
        {{"BMI", AddressingMode::RELATIVE16}, 0x33},
        {{"BNE", AddressingMode::RELATIVE}, 0xD0},
        {{"BNE", AddressingMode::RELATIVE16}, 0xD3},
        {{"BPL", AddressingMode::RELATIVE}, 0x10},
        {{"BPL", AddressingMode::RELATIVE16}, 0x13},
        {{"BRA", AddressingMode::RELATIVE}, 0x80},
        {{"BRA", AddressingMode::RELATIVE16}, 0x83},
        {{"BRK", AddressingMode::IMPLIED}, 0x00},
        {{"BSR", AddressingMode::RELATIVE16}, 0x63},
        {{"BVC", AddressingMode::RELATIVE}, 0x50},
        {{"BVC", AddressingMode::RELATIVE16}, 0x53},
        {{"BVS", AddressingMode::RELATIVE}, 0x70},
        {{"BVS", AddressingMode::RELATIVE16}, 0x73},
        {{"CLC", AddressingMode::IMPLIED}, 0x18},
        {{"CLD", AddressingMode::IMPLIED}, 0xD8},
        {{"CLE", AddressingMode::IMPLIED}, 0x02},
        {{"CLI", AddressingMode::IMPLIED}, 0x58},
        {{"CLV", AddressingMode::IMPLIED}, 0xB8},
        {{"CMP", AddressingMode::BASE_PAGE_INDIRECT_Y}, 0xD1},
        {{"CMP", AddressingMode::BASE_PAGE_INDIRECT_Z}, 0xD2},
        {{"CMP", AddressingMode::FLAT_INDIRECT_Z}, 0xD2},
        {{"CMP", AddressingMode::STACK_RELATIVE}, 0xD2},
        {{"CMP", AddressingMode::BASE_PAGE_X_INDIRECT}, 0xC1},
        {{"CMP", AddressingMode::ABSOLUTE}, 0xCD},
        {{"CMP", AddressingMode::ABSOLUTE_X}, 0xDD},
        {{"CMP", AddressingMode::ABSOLUTE_Y}, 0xD9},
        {{"CMP", AddressingMode::BASE_PAGE}, 0xC5},
        {{"CMP", AddressingMode::BASE_PAGE_X}, 0xD5},
        {{"CMP", AddressingMode::IMMEDIATE}, 0xC9},
        {{"CPX", AddressingMode::ABSOLUTE}, 0xEC},
        {{"CPX", AddressingMode::BASE_PAGE}, 0xE4},
        {{"CPX", AddressingMode::IMMEDIATE}, 0xE0},
        {{"CPY", AddressingMode::ABSOLUTE}, 0xCC},
        {{"CPY", AddressingMode::BASE_PAGE}, 0xC4},
        {{"CPY", AddressingMode::IMMEDIATE}, 0xC0},
        {{"CPZ", AddressingMode::ABSOLUTE}, 0xDC},
        {{"CPZ", AddressingMode::BASE_PAGE}, 0xD4},
        {{"CPZ", AddressingMode::IMMEDIATE}, 0xC2},
        {{"DEC", AddressingMode::ABSOLUTE}, 0xCE},
        {{"DEC", AddressingMode::ABSOLUTE_X}, 0xDE},
        {{"DEC", AddressingMode::ACCUMULATOR}, 0x3A},
        {{"DEC", AddressingMode::BASE_PAGE}, 0xC6},
        {{"DEC", AddressingMode::BASE_PAGE_X}, 0xD6},
        {{"DEW", AddressingMode::BASE_PAGE}, 0xC3},
        {{"DEX", AddressingMode::IMPLIED}, 0xCA},
        {{"DEY", AddressingMode::IMPLIED}, 0x88},
        {{"DEZ", AddressingMode::IMPLIED}, 0x3B},
        {{"EOM", AddressingMode::IMPLIED}, 0xEA},
        {{"EOR", AddressingMode::BASE_PAGE_INDIRECT_Y}, 0x51},
        {{"EOR", AddressingMode::BASE_PAGE_INDIRECT_Z}, 0x52},
        {{"EOR", AddressingMode::FLAT_INDIRECT_Z}, 0x52},
        {{"EOR", AddressingMode::STACK_RELATIVE}, 0x52},
        {{"EOR", AddressingMode::BASE_PAGE_X_INDIRECT}, 0x41},
        {{"EOR", AddressingMode::ABSOLUTE}, 0x4D},
        {{"EOR", AddressingMode::ABSOLUTE_X}, 0x5D},
        {{"EOR", AddressingMode::ABSOLUTE_Y}, 0x59},
        {{"EOR", AddressingMode::BASE_PAGE}, 0x45},
        {{"EOR", AddressingMode::BASE_PAGE_X}, 0x55},
        {{"EOR", AddressingMode::IMMEDIATE}, 0x49},
        {{"INC", AddressingMode::ABSOLUTE}, 0xEE},
        {{"INC", AddressingMode::ABSOLUTE_X}, 0xFE},
        {{"INC", AddressingMode::ACCUMULATOR}, 0x1A},
        {{"INC", AddressingMode::BASE_PAGE}, 0xE6},
        {{"INC", AddressingMode::BASE_PAGE_X}, 0xF6},
        {{"INW", AddressingMode::BASE_PAGE}, 0xE3},
        {{"INX", AddressingMode::IMPLIED}, 0xE8},
        {{"INY", AddressingMode::IMPLIED}, 0xC8},
        {{"INZ", AddressingMode::IMPLIED}, 0x1B},
        {{"JMP", AddressingMode::ABSOLUTE_INDIRECT}, 0x6C},
        {{"JMP", AddressingMode::ABSOLUTE_X_INDIRECT}, 0x7C},
        {{"JMP", AddressingMode::ABSOLUTE}, 0x4C},
        {{"JSR", AddressingMode::ABSOLUTE_INDIRECT}, 0x22},
        {{"JSR", AddressingMode::ABSOLUTE_X_INDIRECT}, 0x23},
        {{"JSR", AddressingMode::ABSOLUTE}, 0x20},
        {{"LDA", AddressingMode::BASE_PAGE_INDIRECT_Y}, 0xB1},
        {{"LDA", AddressingMode::BASE_PAGE_INDIRECT_Z}, 0xB2},
        {{"LDA", AddressingMode::FLAT_INDIRECT_Z}, 0xB2},
        {{"LDA", AddressingMode::STACK_RELATIVE}, 0xE2},
        {{"LDA", AddressingMode::BASE_PAGE_X_INDIRECT}, 0xA1},
        {{"LDA", AddressingMode::ABSOLUTE}, 0xAD},
        {{"LDA", AddressingMode::ABSOLUTE_X}, 0xBD},
        {{"LDA", AddressingMode::ABSOLUTE_Y}, 0xB9},
        {{"LDA", AddressingMode::BASE_PAGE}, 0xA5},
        {{"LDA", AddressingMode::BASE_PAGE_X}, 0xB5},
        {{"LDA", AddressingMode::IMMEDIATE}, 0xA9},
        {{"LDX", AddressingMode::ABSOLUTE}, 0xAE},
        {{"LDX", AddressingMode::ABSOLUTE_Y}, 0xBE},
        {{"LDX", AddressingMode::BASE_PAGE}, 0xA6},
        {{"LDX", AddressingMode::BASE_PAGE_Y}, 0xB6},
        {{"LDX", AddressingMode::IMMEDIATE}, 0xA2},
        {{"LDY", AddressingMode::ABSOLUTE}, 0xAC},
        {{"LDY", AddressingMode::ABSOLUTE_X}, 0xBC},
        {{"LDY", AddressingMode::BASE_PAGE}, 0xA4},
        {{"LDY", AddressingMode::BASE_PAGE_X}, 0xB4},
        {{"LDY", AddressingMode::IMMEDIATE}, 0xA0},
        {{"LDZ", AddressingMode::ABSOLUTE}, 0xAB},
        {{"LDZ", AddressingMode::ABSOLUTE_X}, 0xBB},
        {{"LDZ", AddressingMode::IMMEDIATE}, 0xA3},
        {{"LDQ", AddressingMode::BASE_PAGE}, 0xA5},
        {{"LDQ", AddressingMode::ABSOLUTE}, 0xAD},
        {{"LDQ", AddressingMode::BASE_PAGE_INDIRECT_Z}, 0xB2},
        {{"LDQ", AddressingMode::FLAT_INDIRECT_Z}, 0xB2},
        {{"LSR", AddressingMode::ABSOLUTE}, 0x4E},
        {{"LSR", AddressingMode::ABSOLUTE_X}, 0x5E},
        {{"LSR", AddressingMode::ACCUMULATOR}, 0x4A},
        {{"LSR", AddressingMode::BASE_PAGE}, 0x46},
        {{"LSR", AddressingMode::BASE_PAGE_X}, 0x56},
        {{"MAP", AddressingMode::IMPLIED}, 0x5C},
        {{"NEG", AddressingMode::ACCUMULATOR}, 0x42},
        {{"NOP", AddressingMode::IMPLIED}, 0xEA},
        {{"ORA", AddressingMode::BASE_PAGE_INDIRECT_Y}, 0x11},
        {{"ORA", AddressingMode::BASE_PAGE_INDIRECT_Z}, 0x12},
        {{"ORA", AddressingMode::FLAT_INDIRECT_Z}, 0x12},
        {{"ORA", AddressingMode::STACK_RELATIVE}, 0x12},
        {{"ORA", AddressingMode::BASE_PAGE_X_INDIRECT}, 0x01},
        {{"ORA", AddressingMode::ABSOLUTE}, 0x0D},
        {{"ORA", AddressingMode::ABSOLUTE_X}, 0x1D},
        {{"ORA", AddressingMode::ABSOLUTE_Y}, 0x19},
        {{"ORA", AddressingMode::BASE_PAGE}, 0x05},
        {{"ORA", AddressingMode::BASE_PAGE_X}, 0x15},
        {{"ORA", AddressingMode::IMMEDIATE}, 0x09},
        {{"PHA", AddressingMode::IMPLIED}, 0x48},
        {{"PHP", AddressingMode::IMPLIED}, 0x08},
        {{"PHW", AddressingMode::ABSOLUTE}, 0xFC},
        {{"PHW", AddressingMode::IMMEDIATE16}, 0xF4},
        {{"PHX", AddressingMode::IMPLIED}, 0xDA},
        {{"PHY", AddressingMode::IMPLIED}, 0x5A},
        {{"PHZ", AddressingMode::IMPLIED}, 0xDB},
        {{"PLA", AddressingMode::IMPLIED}, 0x68},
        {{"PLP", AddressingMode::IMPLIED}, 0x28},
        {{"PLX", AddressingMode::IMPLIED}, 0xFA},
        {{"PLY", AddressingMode::IMPLIED}, 0x7A},
        {{"PLZ", AddressingMode::IMPLIED}, 0xFB},
        {{"RMB0", AddressingMode::BASE_PAGE}, 0x07},
        {{"RMB1", AddressingMode::BASE_PAGE}, 0x17},
        {{"RMB2", AddressingMode::BASE_PAGE}, 0x27},
        {{"RMB3", AddressingMode::BASE_PAGE}, 0x37},
        {{"RMB4", AddressingMode::BASE_PAGE}, 0x47},
        {{"RMB5", AddressingMode::BASE_PAGE}, 0x57},
        {{"RMB6", AddressingMode::BASE_PAGE}, 0x67},
        {{"RMB7", AddressingMode::BASE_PAGE}, 0x77},
        {{"ROL", AddressingMode::ABSOLUTE}, 0x2E},
        {{"ROL", AddressingMode::ABSOLUTE_X}, 0x3E},
        {{"ROL", AddressingMode::ACCUMULATOR}, 0x2A},
        {{"ROL", AddressingMode::BASE_PAGE}, 0x26},
        {{"ROL", AddressingMode::BASE_PAGE_X}, 0x36},
        {{"ROR", AddressingMode::ABSOLUTE}, 0x6E},
        {{"ROR", AddressingMode::ABSOLUTE_X}, 0x7E},
        {{"ROR", AddressingMode::ACCUMULATOR}, 0x6A},
        {{"ROR", AddressingMode::BASE_PAGE}, 0x66},
        {{"ROR", AddressingMode::BASE_PAGE_X}, 0x76},
        {{"ROW", AddressingMode::ABSOLUTE}, 0xEB},
        {{"RTI", AddressingMode::IMPLIED}, 0x40},
        {{"RTS", AddressingMode::IMMEDIATE}, 0x62},
        {{"RTS", AddressingMode::IMPLIED}, 0x60},
        {{"SBC", AddressingMode::BASE_PAGE_INDIRECT_Y}, 0xF1},
        {{"SBC", AddressingMode::BASE_PAGE_INDIRECT_Z}, 0xF2},
        {{"SBC", AddressingMode::FLAT_INDIRECT_Z}, 0xF2},
        {{"SBC", AddressingMode::STACK_RELATIVE}, 0xF2},
        {{"SBC", AddressingMode::BASE_PAGE_X_INDIRECT}, 0xE1},
        {{"SBC", AddressingMode::ABSOLUTE}, 0xED},
        {{"SBC", AddressingMode::ABSOLUTE_X}, 0xFD},
        {{"SBC", AddressingMode::ABSOLUTE_Y}, 0xF9},
        {{"SBC", AddressingMode::BASE_PAGE}, 0xE5},
        {{"SBC", AddressingMode::BASE_PAGE_X}, 0xF5},
        {{"SBC", AddressingMode::IMMEDIATE}, 0xE9},
        {{"SEC", AddressingMode::IMPLIED}, 0x38},
        {{"SED", AddressingMode::IMPLIED}, 0xF8},
        {{"SEE", AddressingMode::IMPLIED}, 0x03},
        {{"SEI", AddressingMode::IMPLIED}, 0x78},
        {{"SMB0", AddressingMode::BASE_PAGE}, 0x87},
        {{"SMB1", AddressingMode::BASE_PAGE}, 0x97},
        {{"SMB2", AddressingMode::BASE_PAGE}, 0xA7},
        {{"SMB3", AddressingMode::BASE_PAGE}, 0xB7},
        {{"SMB4", AddressingMode::BASE_PAGE}, 0xC7},
        {{"SMB5", AddressingMode::BASE_PAGE}, 0xD7},
        {{"SMB6", AddressingMode::BASE_PAGE}, 0xE7},
        {{"SMB7", AddressingMode::BASE_PAGE}, 0xF7},
        {{"STA", AddressingMode::BASE_PAGE_INDIRECT_Y}, 0x91},
        {{"STA", AddressingMode::BASE_PAGE_INDIRECT_Z}, 0x92},
        {{"STA", AddressingMode::FLAT_INDIRECT_Z}, 0x92},
        {{"STA", AddressingMode::STACK_RELATIVE}, 0x82},
        {{"STA", AddressingMode::BASE_PAGE_X_INDIRECT}, 0x81},
        {{"STA", AddressingMode::ABSOLUTE}, 0x8D},
        {{"STA", AddressingMode::ABSOLUTE_X}, 0x9D},
        {{"STA", AddressingMode::ABSOLUTE_Y}, 0x99},
        {{"STA", AddressingMode::BASE_PAGE}, 0x85},
        {{"STA", AddressingMode::BASE_PAGE_X}, 0x95},
        {{"STX", AddressingMode::ABSOLUTE}, 0x8E},
        {{"STX", AddressingMode::ABSOLUTE_Y}, 0x9B},
        {{"STX", AddressingMode::BASE_PAGE}, 0x86},
        {{"STX", AddressingMode::BASE_PAGE_Y}, 0x96},
        {{"STY", AddressingMode::ABSOLUTE}, 0x8C},
        {{"STY", AddressingMode::ABSOLUTE_X}, 0x8B},
        {{"STY", AddressingMode::BASE_PAGE}, 0x84},
        {{"STY", AddressingMode::BASE_PAGE_X}, 0x94},
        {{"STZ", AddressingMode::ABSOLUTE}, 0x9C},
        {{"STZ", AddressingMode::ABSOLUTE_X}, 0x9E},
        {{"STZ", AddressingMode::BASE_PAGE}, 0x64},
        {{"STZ", AddressingMode::BASE_PAGE_X}, 0x74},
        {{"STQ", AddressingMode::BASE_PAGE}, 0x85},
        {{"STQ", AddressingMode::ABSOLUTE}, 0x8D},
        {{"STQ", AddressingMode::BASE_PAGE_INDIRECT_Z}, 0x92},
        {{"STQ", AddressingMode::FLAT_INDIRECT_Z}, 0x92},
        {{"TAB", AddressingMode::IMPLIED}, 0x5B},
        {{"TAX", AddressingMode::IMPLIED}, 0xAA},
        {{"TAY", AddressingMode::IMPLIED}, 0xA8},
        {{"TAZ", AddressingMode::IMPLIED}, 0x4B},
        {{"TBA", AddressingMode::IMPLIED}, 0x7B},
        {{"TRB", AddressingMode::ABSOLUTE}, 0x1C},
        {{"TRB", AddressingMode::BASE_PAGE}, 0x14},
        {{"TSB", AddressingMode::ABSOLUTE}, 0x0C},
        {{"TSB", AddressingMode::BASE_PAGE}, 0x04},
        {{"TSX", AddressingMode::IMPLIED}, 0xBA},
        {{"TSY", AddressingMode::IMPLIED}, 0x0B},
        {{"TXA", AddressingMode::IMPLIED}, 0x8A},
        {{"TXS", AddressingMode::IMPLIED}, 0x9A},
        {{"TYA", AddressingMode::IMPLIED}, 0x98},
        {{"TYS", AddressingMode::IMPLIED}, 0x2B},
        {{"TZA", AddressingMode::IMPLIED}, 0x6B},
    };
    return opcodes;
}

uint8_t AssemblerOpcodeDatabase::getOpcode(const std::string& m, AddressingMode mode) {
    std::string baseM = m;
    if (m.size() > 1 && m.back() == 'Q' && m != "LDQ" && m != "STQ" && m.substr(0, 3) != "BEQ" && m.substr(0, 3) != "BNE" && m.substr(0, 3) != "BRA" && m.substr(0, 3) != "BSR") 
        baseM = m.substr(0, m.size() - 1);

    const auto& opMap = getOpcodeMap();
    auto it = opMap.find({baseM, mode});
    if (it != opMap.end()) return it->second;
    return 0;
}

std::vector<AddressingMode> AssemblerOpcodeDatabase::getValidAddressingModes(const std::string& mnemonic) {
    std::string baseM = mnemonic;
    if (mnemonic.size() > 1 && mnemonic.back() == 'Q' && mnemonic != "LDQ" && mnemonic != "STQ" && mnemonic.substr(0, 3) != "BEQ" && mnemonic.substr(0, 3) != "BNE" && mnemonic.substr(0, 3) != "BRA" && mnemonic.substr(0, 3) != "BSR") 
        baseM = mnemonic.substr(0, mnemonic.size() - 1);

    std::vector<AddressingMode> modes;
    const auto& opMap = getOpcodeMap();
    for (const auto& entry : opMap) {
        if (entry.first.first == baseM) modes.push_back(entry.first.second);
    }
    return modes;
}

std::string AssemblerOpcodeDatabase::AddressingModeToString(AddressingMode mode) {
    switch (mode) {
        case AddressingMode::IMPLIED: return "Implied";
        case AddressingMode::ACCUMULATOR: return "A";
        case AddressingMode::IMMEDIATE: return "#imm";
        case AddressingMode::IMMEDIATE16: return "#imm16";
        case AddressingMode::BASE_PAGE: return "zp";
        case AddressingMode::BASE_PAGE_X: return "zp,X";
        case AddressingMode::BASE_PAGE_Y: return "zp,Y";
        case AddressingMode::ABSOLUTE: return "abs";
        case AddressingMode::ABSOLUTE_X: return "abs,X";
        case AddressingMode::ABSOLUTE_Y: return "abs,Y";
        case AddressingMode::INDIRECT: return "(zp)";
        case AddressingMode::BASE_PAGE_X_INDIRECT: return "(zp,X)";
        case AddressingMode::BASE_PAGE_INDIRECT_Y: return "(zp),Y";
        case AddressingMode::BASE_PAGE_INDIRECT_Z: return "(zp),Z";
        case AddressingMode::BASE_PAGE_INDIRECT_SP_Y: return "(zp,SP),Y";
        case AddressingMode::ABSOLUTE_INDIRECT: return "(abs)";
        case AddressingMode::ABSOLUTE_X_INDIRECT: return "(abs,X)";
        case AddressingMode::RELATIVE: return "rel";
        case AddressingMode::RELATIVE16: return "rel16";
        case AddressingMode::BASE_PAGE_RELATIVE: return "zp,rel";
        case AddressingMode::STACK_RELATIVE: return "offset,s";
        case AddressingMode::STACK_RELATIVE_INDIRECT_Y: return "(offset,s),y";
        case AddressingMode::LINEAR_ABSOLUTE: return "lin_abs";
        case AddressingMode::LINEAR_ABSOLUTE_X: return "lin_abs,X";
        case AddressingMode::LINEAR_ABSOLUTE_Y: return "lin_abs,Y";
        case AddressingMode::FLAT_INDIRECT_Z: return "[zp],Z";
        case AddressingMode::QUAD_Q: return "Q";
        case AddressingMode::NONE: return "None";
        default: return "Unknown";
    }
}
