#include "CodeGenerator.hpp"
#include <iostream>
#include <iomanip>
#include <sstream>

// TODO: Implement a better register allocation strategy instead of relying on fixed zero-page scratch space.

CodeGenerator::CodeGenerator(std::ostream& out) : out(out) {}

void CodeGenerator::generate(TranslationUnit& unit) {
    emitter = std::make_unique<M65Emitter>(out, zeroPageStart);
    unit.accept(*this);
    emitData();
}

void CodeGenerator::emit(const std::string& line) {
    out << "    " << line << std::endl;
}

std::string CodeGenerator::newLabel() {
    return "L" + std::to_string(labelCount++);
}

static CodeGenerator::ExpressionType getExprType(Expression* expr, const std::map<std::string, CodeGenerator::VarInfo>& variableTypes) {
    if (auto* ref = dynamic_cast<VariableReference*>(expr)) {
        if (variableTypes.count(ref->name)) {
            return {variableTypes.at(ref->name).type, variableTypes.at(ref->name).pointerLevel};
        }
    }
    if (auto* bin = dynamic_cast<BinaryOperation*>(expr)) { return getExprType(bin->left.get(), variableTypes); }
    if (auto* un = dynamic_cast<UnaryOperation*>(expr)) {
        CodeGenerator::ExpressionType sub = getExprType(un->operand.get(), variableTypes);
        if (un->op == "*") return {sub.type, sub.pointerLevel > 0 ? sub.pointerLevel - 1 : 0};
        if (un->op == "&") return {sub.type, sub.pointerLevel + 1};
        return sub;
    }
    return {"int", 0};
}

void CodeGenerator::visit(TranslationUnit& node) {
    out << "; Generated by cc45" << std::endl;
    out << ".org $2000" << std::endl << std::endl;
    out << ".var printf = $0000 ; Placeholder for external symbol" << std::endl;
    for (auto& func : node.functions) {
        func->accept(*this);
    }
}


void CodeGenerator::visit(FunctionDeclaration& node) {
    std::string procLine = "PROC " + node.name;
    currentVars.clear();
    variableTypes.clear();
    for (const auto& param : node.parameters) {
        variableTypes[param.name] = {param.type, param.pointerLevel};
        if (param.pointerLevel > 0) {
            procLine += ", W#" + param.name;
        } else if (param.type == "char") {
            procLine += ", B#" + param.name;
        } else {
            procLine += ", W#" + param.name;
        }
        currentVars.push_back(param.name);
    }
    out << procLine << std::endl;
    node.body->accept(*this);
    emit("ENDPROC");
    out << std::endl;
}

void CodeGenerator::visit(CompoundStatement& node) {
    for (auto& stmt : node.statements) stmt->accept(*this);
}

void CodeGenerator::visit(VariableDeclaration& node) {
    variableTypes[node.name] = {node.type, node.pointerLevel};
    int size = (node.pointerLevel > 0) ? 2 : ((node.type == "char") ? 1 : 2);
    if (node.initializer) {
        node.initializer->accept(*this);
        if (size == 2) emitter->push_ax();
        else emitter->pha();
    } else {
        if (size == 2) emit("PHW #$0000");
        else { emitter->lda_imm(0); emitter->pha(); }
    }
    for (const auto& varName : currentVars) {
        emit(".var " + varName + " = " + varName + " + " + std::to_string(size));
    }
    emit(".var " + node.name + " = " + std::to_string(size));
    currentVars.push_back(node.name);
    emit(".cleanup " + std::to_string(size));
}

void CodeGenerator::visit(Assignment& node) {
    if (auto* ref = dynamic_cast<VariableReference*>(node.target.get())) {
        node.expression->accept(*this);
        emit("STA " + ref->name + ", s");
        if (variableTypes.count(ref->name) && (variableTypes[ref->name].pointerLevel > 0 || variableTypes[ref->name].type != "char")) {
            emit("PHA");
            emit("TXA");
            emit("STA " + ref->name + "+1, s");
            emit("PLA");
        }
    } else if (auto* un = dynamic_cast<UnaryOperation*>(node.target.get())) {
        if (un->op == "*") {
            // *ptr = val
            un->operand->accept(*this);
            emitter->sta_s(0); emitter->stx_s(1); // ptr in ZP scratch 0,1
            node.expression->accept(*this);
            // value in AX
            emitter->sta_ind_z(emitter->getZP(0), false);
            ExpressionType subType = getExprType(un->operand.get(), variableTypes);
            if (subType.type != "char" || subType.pointerLevel > 1) {
                emitter->txa();
                emitter->ldy_imm(1);
                std::stringstream ss;
                ss << std::hex << std::uppercase << std::setfill('0') << std::setw(2) << (int)emitter->getZP(0);
                emit("STA ($" + ss.str() + "),Y");
            }
        }
    }
}

void CodeGenerator::visit(ReturnStatement& node) {
    if (node.expression) node.expression->accept(*this);
    emit("ENDPROC");
}

void CodeGenerator::visit(ExpressionStatement& node) { node.expression->accept(*this); }

void CodeGenerator::visit(IfStatement& node) {
    std::string labelElse = newLabel(); std::string labelEnd = newLabel();
    node.condition->accept(*this);
    emit("CMP #$00"); emit("BEQ " + labelElse);
    node.thenBranch->accept(*this);
    if (node.elseBranch) { emit("BRA " + labelEnd); out << labelElse << ":" << std::endl; node.elseBranch->accept(*this); out << labelEnd << ":" << std::endl; }
    else { out << labelElse << ":" << std::endl; }
}

void CodeGenerator::visit(WhileStatement& node) {
    std::string labelStart = newLabel(); std::string labelEnd = newLabel();
    out << labelStart << ":" << std::endl;
    node.condition->accept(*this);
    emit("CMP #$00"); emit("BEQ " + labelEnd);
    node.body->accept(*this);
    emit("BRA " + labelStart);
    out << labelEnd << ":" << std::endl;
}

void CodeGenerator::visit(DoWhileStatement& node) {
    std::string labelStart = newLabel();
    out << labelStart << ":" << std::endl;
    node.body->accept(*this);
    node.condition->accept(*this);
    emit("CMP #$00"); emit("BNE " + labelStart);
}

void CodeGenerator::visit(ForStatement& node) {
    if (node.initializer) node.initializer->accept(*this);
    std::string labelStart = newLabel(); std::string labelEnd = newLabel();
    out << labelStart << ":" << std::endl;
    if (node.condition) { node.condition->accept(*this); emit("CMP #$00"); emit("BEQ " + labelEnd); }
    node.body->accept(*this);
    if (node.increment) node.increment->accept(*this);
    emit("BRA " + labelStart);
    out << labelEnd << ":" << std::endl;
}

void CodeGenerator::visit(AsmStatement& node) { emit(node.code); }
void CodeGenerator::visit(IntegerLiteral& node) { emitter->lda_imm(node.value & 0xFF); emitter->ldx_imm((node.value >> 8) & 0xFF); }
void CodeGenerator::visit(StringLiteral& node) {
    if (stringPool.find(node.value) == stringPool.end()) stringPool[node.value] = "STR" + std::to_string(stringCount++);
    std::string label = stringPool[node.value];
    emit("LDA #<" + label); emit("LDX #>" + label);
}
void CodeGenerator::visit(VariableReference& node) {
    emit("LDA " + node.name + ", s");
    if (variableTypes.count(node.name) && variableTypes[node.name].type == "char" && variableTypes[node.name].pointerLevel == 0) {
        emitter->ldx_imm(0);
    } else {
        emit("PHA");
        emit("LDA " + node.name + "+1, s");
        emit("TAX");
        emit("PLA");
    }
}
void CodeGenerator::visit(FunctionCall& node) {
    for (auto& arg : node.arguments) {
        arg->accept(*this);
        emitter->push_ax();
    }
    emit("JSR " + node.name);
    if (!node.arguments.empty()) emit("RTN #" + std::to_string(node.arguments.size() * 2));
}

void CodeGenerator::emitData() {
    out << std::endl << "; Data Section" << std::endl;
    for (const auto& entry : stringPool) {
        out << entry.second << ":" << std::endl;
        out << "    .text \"" << entry.first << "\"" << std::endl;
        out << "    .byte 0" << std::endl;
    }
}

void CodeGenerator::visit(BinaryOperation& node) {
    ExpressionType lhsType = getExprType(node.left.get(), variableTypes);
    ExpressionType rhsType = getExprType(node.right.get(), variableTypes);
    int scale = 1;
    if (lhsType.pointerLevel > 0 && rhsType.pointerLevel == 0 && (node.op == "+" || node.op == "-")) {
        scale = (lhsType.type == "char" && lhsType.pointerLevel == 1) ? 1 : 2;
    }

    bool isLiteralOne = false;
    if (scale == 1) {
        if (auto* lit = dynamic_cast<IntegerLiteral*>(node.right.get())) {
            if (lit->value == 1) isLiteralOne = true;
        }
    }

    if (isLiteralOne && (node.op == "+" || node.op == "-")) {
        node.left->accept(*this);
        if (node.op == "+") {
            std::string label = newLabel();
            emitter->inc_a(); emitter->bne(0x02); emit("INX");
            out << label << ":" << std::endl;
        } else {
            std::string label = newLabel();
            emit("CMP #$00"); emit("BNE " + label); emit("DEX");
            out << label << ":" << std::endl; emitter->dec_a();
        }
        return;
    }

    node.left->accept(*this);
    int lhsSize = 2;
    if (auto* ref = dynamic_cast<VariableReference*>(node.left.get())) {
        if (variableTypes.count(ref->name) && variableTypes[ref->name].type == "char" && variableTypes[ref->name].pointerLevel == 0) lhsSize = 1;
    }
    if (lhsSize == 2) emitter->push_ax(); else emitter->pha();
    for (const auto& varName : currentVars) emit(".var " + varName + " = " + varName + " + " + std::to_string(lhsSize));
    
    node.right->accept(*this);
    if (scale > 1) { emitter->asl_a(); emit("ROL X"); }
    
    if (node.op == "+") {
        if (lhsSize == 1) { emitter->clc(); emit("ADC 1, s"); emitter->ldx_imm(0); }
        else { emitter->sta_s(0); emitter->stx_s(1); emit("LDA 2, s"); emitter->clc(); emitter->adc_s(0); emitter->pha(); emit("LDA 3, s"); emitter->adc_s(1); emitter->tax(); emitter->pla(); }
    } else if (node.op == "-") {
        if (lhsSize == 1) { emitter->sta_s(0); emit("LDA 1, s"); emitter->sec(); emitter->sbc_s(0); emitter->ldx_imm(0); }
        else { emitter->sta_s(0); emitter->stx_s(1); emit("LDA 2, s"); emitter->sec(); emitter->sbc_s(0); emitter->pha(); emit("LDA 3, s"); emitter->sbc_s(1); emitter->tax(); emitter->pla(); }
    } else if (node.op == "&") {
        if (lhsSize == 1) { emitter->and_s(0); emitter->ldx_imm(0); }
        else { emit("AND 2, s"); emitter->pha(); emitter->txa(); emit("AND 3, s"); emitter->tax(); emitter->pla(); }
    } else if (node.op == "|") {
        if (lhsSize == 1) { emitter->ora_s(0); emitter->ldx_imm(0); }
        else { emit("ORA 2, s"); emitter->pha(); emitter->txa(); emit("ORA 3, s"); emitter->tax(); emitter->pla(); }
    } else if (node.op == "^") {
        if (lhsSize == 1) { emitter->eor_s(0); emitter->ldx_imm(0); }
        else { emit("EOR 2, s"); emitter->pha(); emitter->txa(); emit("EOR 3, s"); emitter->tax(); emitter->pla(); }
    } else if (node.op == "<<") {
        emitter->sta_s(0); emitter->pop_ax(); std::string label = newLabel(); std::string end = newLabel();
        out << label << ":" << std::endl; emitter->lda_s(0); emitter->beq(0x07); emitter->dec_s(0); emitter->asl_a(); emit("ROL X"); emitter->bra(-11);
        out << end << ":" << std::endl;
    } else if (node.op == "==" || node.op == "!=") {
        if (lhsSize == 1) emit("CMP 1, s"); else emit("CMP 2, s");
        std::string labelFalse = newLabel(); std::string labelEnd = newLabel();
        if (node.op == "==") emit("BNE " + labelFalse); else emit("BEQ " + labelFalse);
        if (lhsSize == 2) { emitter->txa(); emit("CMP 3, s"); if (node.op == "==") emit("BNE " + labelFalse); else emit("BEQ " + labelFalse); }
        emitter->lda_imm(1); emitter->bra(0x02);
        out << labelFalse << ":" << std::endl; emitter->lda_imm(0);
        out << labelEnd << ":" << std::endl; emitter->ldx_imm(0);
    } else if (node.op == "*") {
        emit("mul.16 .AX, " + std::to_string(lhsSize) + ", s");
    } else if (node.op == "/") {
        emitter->sta_s(0); emitter->stx_s(1);
        if (lhsSize == 1) { emitter->lda_stack(1); emitter->ldx_imm(0); }
        else { emit("LDA 3, s"); emit("TAX"); emit("LDA 2, s"); }
        emit("div.16 .AX, " + std::to_string((int)emitter->getZP(0)));
    }
    emit("RTN #" + std::to_string(lhsSize));
    for (const auto& varName : currentVars) emit(".var " + varName + " = " + varName + " - " + std::to_string(lhsSize));
}

void CodeGenerator::visit(UnaryOperation& node) {
    if (node.op == "*") {
        node.operand->accept(*this);
        // address in AX
        emitter->sta_s(0); emitter->stx_s(1); // Pointer in ZP 0,1
        emitter->lda_ind_z(emitter->getZP(0), false); // LDA (ZP),Y with Y=0
        ExpressionType subType = getExprType(node.operand.get(), variableTypes);
        if (subType.type == "char" && subType.pointerLevel == 1) {
            emitter->ldx_imm(0);
        } else {
            emitter->pha();
            emitter->ldy_imm(1);
            std::stringstream ss;
            ss << std::hex << std::uppercase << std::setfill('0') << std::setw(2) << (int)emitter->getZP(0);
            emit("LDA ($" + ss.str() + "),Y");
            emitter->tax();
            emitter->pla();
        }
    } else if (node.op == "&") {
        if (auto* ref = dynamic_cast<VariableReference*>(node.operand.get())) {
            // Get address of stack variable: SP + offset
            emitter->tsx();
            emitter->txa();
            emitter->clc();
            emit("ADC #" + ref->name);
            emitter->pha();
            emitter->lda_imm(0); // Assume stack is in ZP/Base page $0000
            emitter->adc_imm(0);
            emitter->tax();
            emitter->pla();
        }
    } else {
        node.operand->accept(*this);
        if (node.op == "!") {
            std::string labelFalse = newLabel(); std::string labelEnd = newLabel();
            emit("CMP #$00"); emit("BNE " + labelFalse); emitter->txa(); emit("BNE " + labelFalse);
            emitter->lda_imm(1); emitter->bra(0x02);
            out << labelFalse << ":" << std::endl; emitter->lda_imm(0);
            out << labelEnd << ":" << std::endl; emitter->ldx_imm(0);
        } else if (node.op == "~") { emitter->not_16(); }
        else if (node.op == "-") { emitter->neg_16(); }
    }
}
