#include "CodeGenerator.hpp"
#include <iostream>

CodeGenerator::CodeGenerator(std::ostream& out) : out(out) {}

void CodeGenerator::generate(TranslationUnit& unit) {
    unit.accept(*this);
    emitData();
}

void CodeGenerator::emit(const std::string& line) {
    out << "    " << line << std::endl;
}

void CodeGenerator::visit(TranslationUnit& node) {
    out << "; Generated by cc45" << std::endl;
    out << ".org $2000" << std::endl << std::endl;
    for (auto& func : node.functions) func->accept(*this);
}

void CodeGenerator::visit(FunctionDeclaration& node) {
    std::string procLine = "PROC " + node.name;
    for (const auto& param : node.parameters) procLine += ", W#" + param.name;
    out << procLine << std::endl;
    node.body->accept(*this);
    emit("ENDPROC"); // Ensure ENDPROC is always there
    out << std::endl;
}

void CodeGenerator::visit(CompoundStatement& node) {
    for (auto& stmt : node.statements) stmt->accept(*this);
}

void CodeGenerator::visit(ReturnStatement& node) {
    node.expression->accept(*this);
    // Assuming result is in A/X
    emit("ENDPROC");
}

void CodeGenerator::visit(ExpressionStatement& node) {
    node.expression->accept(*this);
}

void CodeGenerator::visit(FunctionCall& node) {
    // To handle nested calls, we first evaluate all arguments.
    // If an argument is a function call, we call it, then push its result.
    // The main problem is that CALL <name>, arg1... wants to do the pushing itself.
    // So for complex arguments, we'll manually push and then use a raw JSR.
    
    int bytesPushed = 0;
    for (auto& arg : node.arguments) {
        if (auto* lit = dynamic_cast<IntegerLiteral*>(arg.get())) {
            emit("PHW #$" + std::to_string(lit->value));
            bytesPushed += 2;
        } else if (auto* str = dynamic_cast<StringLiteral*>(arg.get())) {
            if (stringPool.find(str->value) == stringPool.end()) stringPool[str->value] = "str" + std::to_string(stringCount++);
            emit("PHW #" + stringPool[str->value]);
            bytesPushed += 2;
        } else if (auto* var = dynamic_cast<VariableReference*>(arg.get())) {
            // Assume 16-bit for now
            emit("LDA " + var->name + ", s"); // Low
            emit("PHA");
            emit("LDA " + var->name + "+1, s"); // High (simulated)
            emit("PHA");
            bytesPushed += 2;
        } else if (auto* nested = dynamic_cast<FunctionCall*>(arg.get())) {
            nested->accept(*this);
            // Result in A/X (simulated)
            emit("PHX");
            emit("PHA");
            bytesPushed += 2;
        }
    }
    
    emit("JSR " + node.name);
}

void CodeGenerator::visit(VariableReference& node) {
    // For standalone var ref (e.g. return x;), load into A/X
    emit("LDA " + node.name + ", s");
}

void CodeGenerator::visit(IntegerLiteral& node) {
    emit("LDA #$" + std::to_string(node.value));
}

void CodeGenerator::visit(StringLiteral& node) {
}

void CodeGenerator::emitData() {
    if (stringPool.empty()) return;
    out << "; Data Section" << std::endl;
    for (const auto& entry : stringPool) {
        out << entry.second << ":" << std::endl;
        out << "    .text \"" << entry.first << "\"" << std::endl;
        out << "    .byte 0" << std::endl;
    }
}
