; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _memcmp
.extern _memcpy
.extern _memset
.global _main

; [test_memops.c:25] char src[8];
; [test_memops.c:26] char dst[8];
.code
proc _main
    .var _fp = 0
; [test_memops.c:30]     memset(src, 0x42, 4);
    ptrstack _src
    push    a
    ldax #$0042
    push    .ax
    ldax #$0004
    push    .ax
    jsr _memset
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_memops.c:31]     if (src[0] != 0x42) return 1;
    ptrstack _src
    stax $02
    zero a, x
    add.16 .ax, $02
    stax $02
    ldy     #$00
    lda     ($02),y
    ldx     #$00
    stax $02
    ldax #$0042
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L2
    lda     #$01
    bra     *+4
@L2:
    lda     #$00
@L3:
    ldx     #$00
    cmp #$00
    beq L0
    ldax #$0001
    rtn #0
L0:
; [test_memops.c:32]     if (src[3] != 0x42) return 2;
    ptrstack _src
    stax $02
    ldax #$0003
    add.16 .ax, $02
    stax $02
    ldy     #$00
    lda     ($02),y
    ldx     #$00
    stax $02
    ldax #$0042
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L6
    lda     #$01
    bra     *+4
@L6:
    lda     #$00
@L7:
    ldx     #$00
    cmp #$00
    beq L4
    ldax #$0002
    rtn #0
L4:
; [test_memops.c:35]     memset(dst, 0, 8);
    ptrstack _dst
    push    a
    zero a, x
    push    .ax
    ldax #$0008
    push    .ax
    jsr _memset
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_memops.c:36]     memcpy(dst, src, 4);
    ptrstack _dst
    push    a
    ptrstack _src
    push    a
    ldax #$0004
    push    .ax
    jsr _memcpy
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_memops.c:37]     if (dst[0] != 0x42) return 3;
    ptrstack _dst
    stax $02
    zero a, x
    add.16 .ax, $02
    stax $02
    ldy     #$00
    lda     ($02),y
    ldx     #$00
    stax $02
    ldax #$0042
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L10
    lda     #$01
    bra     *+4
@L10:
    lda     #$00
@L11:
    ldx     #$00
    cmp #$00
    beq L8
    ldax #$0003
    rtn #0
L8:
; [test_memops.c:38]     if (dst[3] != 0x42) return 4;
    ptrstack _dst
    stax $02
    ldax #$0003
    add.16 .ax, $02
    stax $02
    ldy     #$00
    lda     ($02),y
    ldx     #$00
    stax $02
    ldax #$0042
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L14
    lda     #$01
    bra     *+4
@L14:
    lda     #$00
@L15:
    ldx     #$00
    cmp #$00
    beq L12
    ldax #$0004
    rtn #0
L12:
; [test_memops.c:41]     if (memcmp(src, dst, 4) != 0) return 5;
    ptrstack _src
    push    a
    ptrstack _dst
    push    a
    ldax #$0004
    push    .ax
    jsr _memcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L18
    lda     #$01
    bra     *+4
@L18:
    lda     #$00
@L19:
    ldx     #$00
    cmp #$00
    beq L16
    ldax #$0005
    rtn #0
L16:
; [test_memops.c:44]     dst[2] = 0x41;
    ldax #$0041
    push    .ax
    ptrstack _dst
    stax $02
    ldax #$0002
    add.16 .ax, $02
    stax $02
    pop     .ax
    ldy     #$00
    sta     ($02),y
; [test_memops.c:45]     if (memcmp(src, dst, 4) <= 0) return 6;
    ptrstack _src
    push    a
    ptrstack _dst
    push    a
    ldax #$0004
    push    .ax
    jsr _memcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L24
    bcs @L22
@L24:
    lda     #$01
    bra     *+4
@L22:
    lda     #$00
@L23:
    ldx     #$00
    cmp #$00
    beq L20
    ldax #$0006
    rtn #0
L20:
; [test_memops.c:47]     return 0;
    zero a, x
    rtn #0
    endproc

.global _src
.global _dst

.code
_init_bss:
    rts

.data
; Data Section

.bss
; BSS Section
__bss_start:
_src:
    .res 8
_dst:
    .res 8
__bss_end:

.data
