; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _strchr
.extern _strrchr
.global _main

; [test_strchr.c:25] char msg[8];
.code
proc _main
    .var _fp = 0
; [test_strchr.c:28]     msg[0] = 'a';
    ldax #$0061
    push    .ax
    ptrstack _msg
    stax $02
    zero a, x
    add.16 .ax, $02
    stax $02
    pop     .ax
    ldy     #$00
    sta     ($02),y
; [test_strchr.c:29]     msg[1] = 'b';
    ldax #$0062
    push    .ax
    ptrstack _msg
    stax $02
    ldax #$0001
    add.16 .ax, $02
    stax $02
    pop     .ax
    ldy     #$00
    sta     ($02),y
; [test_strchr.c:30]     msg[2] = 'c';
    ldax #$0063
    push    .ax
    ptrstack _msg
    stax $02
    ldax #$0002
    add.16 .ax, $02
    stax $02
    pop     .ax
    ldy     #$00
    sta     ($02),y
; [test_strchr.c:31]     msg[3] = 'b';
    ldax #$0062
    push    .ax
    ptrstack _msg
    stax $02
    ldax #$0003
    add.16 .ax, $02
    stax $02
    pop     .ax
    ldy     #$00
    sta     ($02),y
; [test_strchr.c:32]     msg[4] = 'd';
    ldax #$0064
    push    .ax
    ptrstack _msg
    stax $02
    ldax #$0004
    add.16 .ax, $02
    stax $02
    pop     .ax
    ldy     #$00
    sta     ($02),y
; [test_strchr.c:33]     msg[5] = 0;
    zero a, x
    push    .ax
    ptrstack _msg
    stax $02
    ldax #$0005
    add.16 .ax, $02
    stax $02
    pop     .ax
    ldy     #$00
    sta     ($02),y
; [test_strchr.c:36]     char *p = strchr(msg, 'b');
    ptrstack _msg
    push    a
    ldax #$0062
    push    .ax
    jsr _strchr
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    push    .ax
    .var _fp = _fp + 2
    .var _l_p = 0
; [test_strchr.c:37]     if (p == (char *)0) return 1;
    ldax _l_p, s
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    bne @L2
    lda     #$01
    bra     *+4
@L2:
    lda     #$00
@L3:
    ldx     #$00
    cmp #$00
    beq L0
    ldax #$0001
    taz     
    pla     
    pla     
    tza     
    rtn #0
L0:
; [test_strchr.c:38]     if (p != msg + 1) return 2;
    ldax _l_p, s
    stax $02
    ptrstack _msg
    inc     a
    bne     *+4
    inx
@L6:
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L7
    lda     #$01
    bra     *+4
@L7:
    lda     #$00
@L8:
    ldx     #$00
    cmp #$00
    beq L4
    ldax #$0002
    taz     
    pla     
    pla     
    tza     
    rtn #0
L4:
; [test_strchr.c:41]     if (strchr(msg, 'z') != (char *)0) return 3;
    ptrstack _msg
    push    a
    ldax #$007A
    push    .ax
    jsr _strchr
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L11
    lda     #$01
    bra     *+4
@L11:
    lda     #$00
@L12:
    ldx     #$00
    cmp #$00
    beq L9
    ldax #$0003
    taz     
    pla     
    pla     
    tza     
    rtn #0
L9:
; [test_strchr.c:44]     p = strrchr(msg, 'b');
    ptrstack _msg
    push    a
    ldax #$0062
    push    .ax
    jsr _strrchr
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax _l_p, s
; [test_strchr.c:45]     if (p == (char *)0) return 4;
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    bne @L15
    lda     #$01
    bra     *+4
@L15:
    lda     #$00
@L16:
    ldx     #$00
    cmp #$00
    beq L13
    ldax #$0004
    taz     
    pla     
    pla     
    tza     
    rtn #0
L13:
; [test_strchr.c:46]     if (p != msg + 3) return 5;
    ldax _l_p, s
    stax $02
    ptrstack _msg
    stax $04
    ldax #$0003
    add.16 .ax, $04
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L19
    lda     #$01
    bra     *+4
@L19:
    lda     #$00
@L20:
    ldx     #$00
    cmp #$00
    beq L17
    ldax #$0005
    taz     
    pla     
    pla     
    tza     
    rtn #0
L17:
; [test_strchr.c:48]     return 0;
    zero a, x
    taz     
    pla     
    pla     
    tza     
    rtn #0
    endproc

.global _msg

.code
_init_bss:
    rts

.data
; Data Section

.bss
; BSS Section
__bss_start:
_msg:
    .res 8
__bss_end:

.data
