; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _strlen
.global _main

.code
proc _main
    .var _fp = 0
; [test_strlen.c:26]     if (strlen("hello") != 5) return 1;
    ldax #<STR0
    push    .ax
    jsr _strlen
    taz     
    pla     
    pla     
    tza     
    stax $02
    ldax #$0005
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L2
    lda     #$01
    bra     *+4
@L2:
    lda     #$00
@L3:
    ldx     #$00
    cmp #$00
    beq L0
    ldax #$0001
    rtn #0
L0:
; [test_strlen.c:27]     if (strlen("") != 0) return 2;
    ldax #<STR1
    push    .ax
    jsr _strlen
    taz     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L6
    lda     #$01
    bra     *+4
@L6:
    lda     #$00
@L7:
    ldx     #$00
    cmp #$00
    beq L4
    ldax #$0002
    rtn #0
L4:
; [test_strlen.c:28]     if (strlen("a") != 1) return 3;
    ldax #<STR2
    push    .ax
    jsr _strlen
    taz     
    pla     
    pla     
    tza     
    stax $02
    ldax #$0001
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L10
    lda     #$01
    bra     *+4
@L10:
    lda     #$00
@L11:
    ldx     #$00
    cmp #$00
    beq L8
    ldax #$0003
    rtn #0
L8:
; [test_strlen.c:29]     if (strlen("abcdefghij") != 10) return 4;
    ldax #<STR3
    push    .ax
    jsr _strlen
    taz     
    pla     
    pla     
    tza     
    stax $02
    ldax #$000A
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L14
    lda     #$01
    bra     *+4
@L14:
    lda     #$00
@L15:
    ldx     #$00
    cmp #$00
    beq L12
    ldax #$0004
    rtn #0
L12:
; [test_strlen.c:30]     return 0;
    zero a, x
    rtn #0
    endproc


.code
_init_bss:
    rts

.data
; Data Section

.data
STR1:
    .text ""
    .byte 0
STR2:
    .text "a"
    .byte 0
STR3:
    .text "abcdefghij"
    .byte 0
STR0:
    .text "hello"
    .byte 0
