; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _strcmp
.global _main

.code
proc _main
    .var _fp = 0
; [test_strcmp.c:27]     if (strcmp("abc", "abc") != 0) return 1;
    ldax #<STR0
    push    .ax
    ldax #<STR0
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L2
    lda     #$01
    bra     *+4
@L2:
    lda     #$00
@L3:
    ldx     #$00
    cmp #$00
    beq L0
    ldax #$0001
    rtn #0
L0:
; [test_strcmp.c:28]     if (strcmp("", "") != 0) return 2;
    ldax #<STR1
    push    .ax
    ldax #<STR1
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L6
    lda     #$01
    bra     *+4
@L6:
    lda     #$00
@L7:
    ldx     #$00
    cmp #$00
    beq L4
    ldax #$0002
    rtn #0
L4:
; [test_strcmp.c:31]     if (strcmp("abc", "abd") >= 0) return 3;
    ldax #<STR0
    push    .ax
    ldax #<STR2
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    bcc @L10
    lda     #$01
    bra     *+4
@L10:
    lda     #$00
@L11:
    ldx     #$00
    cmp #$00
    beq L8
    ldax #$0003
    rtn #0
L8:
; [test_strcmp.c:32]     if (strcmp("abd", "abc") <= 0) return 4;
    ldax #<STR2
    push    .ax
    ldax #<STR0
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L16
    bcs @L14
@L16:
    lda     #$01
    bra     *+4
@L14:
    lda     #$00
@L15:
    ldx     #$00
    cmp #$00
    beq L12
    ldax #$0004
    rtn #0
L12:
; [test_strcmp.c:35]     if (strcmp("ab", "abc") >= 0) return 5;
    ldax #<STR3
    push    .ax
    ldax #<STR0
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    bcc @L19
    lda     #$01
    bra     *+4
@L19:
    lda     #$00
@L20:
    ldx     #$00
    cmp #$00
    beq L17
    ldax #$0005
    rtn #0
L17:
; [test_strcmp.c:36]     if (strcmp("abc", "ab") <= 0) return 6;
    ldax #<STR0
    push    .ax
    ldax #<STR3
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L25
    bcs @L23
@L25:
    lda     #$01
    bra     *+4
@L23:
    lda     #$00
@L24:
    ldx     #$00
    cmp #$00
    beq L21
    ldax #$0006
    rtn #0
L21:
; [test_strcmp.c:38]     return 0;
    zero a, x
    rtn #0
    endproc


.code
_init_bss:
    rts

.data
; Data Section

.data
STR1:
    .text ""
    .byte 0
STR3:
    .text "ab"
    .byte 0
STR0:
    .text "abc"
    .byte 0
STR2:
    .text "abd"
    .byte 0
