; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _strcmp
.extern _strcpy
.extern _strlen
.global _main

; [test_strcpy.c:25] char buf[16];
.code
proc _main
    .var _fp = 0
; [test_strcpy.c:29]     strcpy(buf, "hello");
    ptrstack _buf
    push    a
    ldax #<STR0
    push    .ax
    jsr _strcpy
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_strcpy.c:30]     if (strcmp(buf, "hello") != 0) return 1;
    ptrstack _buf
    push    a
    ldax #<STR0
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L2
    lda     #$01
    bra     *+4
@L2:
    lda     #$00
@L3:
    ldx     #$00
    cmp #$00
    beq L0
    ldax #$0001
    rtn #0
L0:
; [test_strcpy.c:31]     if (strlen(buf) != 5) return 2;
    ptrstack _buf
    push    a
    jsr _strlen
    taz     
    pla     
    pla     
    tza     
    stax $02
    ldax #$0005
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L6
    lda     #$01
    bra     *+4
@L6:
    lda     #$00
@L7:
    ldx     #$00
    cmp #$00
    beq L4
    ldax #$0002
    rtn #0
L4:
; [test_strcpy.c:34]     strcpy(buf, "");
    ptrstack _buf
    push    a
    ldax #<STR1
    push    .ax
    jsr _strcpy
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_strcpy.c:35]     if (strlen(buf) != 0) return 3;
    ptrstack _buf
    push    a
    jsr _strlen
    taz     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L10
    lda     #$01
    bra     *+4
@L10:
    lda     #$00
@L11:
    ldx     #$00
    cmp #$00
    beq L8
    ldax #$0003
    rtn #0
L8:
; [test_strcpy.c:37]     return 0;
    zero a, x
    rtn #0
    endproc

.global _buf

.code
_init_bss:
    rts

.data
; Data Section

.bss
; BSS Section
__bss_start:
_buf:
    .res 16
__bss_end:

.data
STR1:
    .text ""
    .byte 0
STR0:
    .text "hello"
    .byte 0
