; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _printf
.extern _puts
.global _main
.extern __sp_base

; [main.c:70] vic_ctrl_a    *VICIV_CTRL_A = 0xD031;
; [main.c:71] vic_ctrl_b    *VICIV_CTRL_B = 0xD054;
; [main.c:72] sprite_enable *SPR_ENABLE   = 0xD015;
; [main.c:75] screen_char *SCREEN = 0x0800;
.code
proc _unlock_mega65_io
    .var _fp = 0
; [main.c:78]     asm("lda #$47");
    lda #$47
; [main.c:79]     asm("sta $d02f");
    sta $d02f
; [main.c:80]     asm("lda #$53");
    lda #$53
; [main.c:81]     asm("sta $d02f");
    sta $d02f
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _print_ctrl_a
    .var _fp = 0
    ; frame: 1 bytes
    lda     #$00
    pha     
    .local _l_reg = 0
; [main.c:85]     vic_ctrl_a reg;
; [main.c:87]     reg = *VICIV_CTRL_A;
    ldax _VICIV_CTRL_A
    stax $03
    ptrderef $03
    sta.sp _l_reg
; [main.c:89]     printf("vic ctrl a ($d031):\n");
    ldax #STR0
    push    .ax
    .var _fp = _fp + 2
    jsr _printf
    taz     
    pla     
    pla     
    tza     
    .var _fp = _fp - 2
; [main.c:90]     printf("  h640=%d fast=%d attr=%d\n",
; [main.c:91]            reg.h640, reg.fast, reg.attr);
    lda.sp _l_reg
    ldx     #$00
    bfext #2, #1
    push    .ax
    .var _fp = _fp + 2
    lda.sp _l_reg
    ldx     #$00
    bfext #1, #1
    push    .ax
    .var _fp = _fp + 2
    lda.sp _l_reg
    ldx     #$00
    bfext #0, #1
    push    .ax
    .var _fp = _fp + 2
    ldax #STR1
    push    .ax
    .var _fp = _fp + 2
    jsr _printf
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 8
; [main.c:92]     printf("  bpm=%d v400=%d chr16=%d\n",
; [main.c:93]            reg.bpm, reg.v400, reg.chr16);
    lda.sp _l_reg
    ldx     #$00
    bfext #5, #1
    push    .ax
    .var _fp = _fp + 2
    lda.sp _l_reg
    ldx     #$00
    bfext #4, #1
    push    .ax
    .var _fp = _fp + 2
    lda.sp _l_reg
    ldx     #$00
    bfext #3, #1
    push    .ax
    .var _fp = _fp + 2
    ldax #STR2
    push    .ax
    .var _fp = _fp + 2
    jsr _printf
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 8
    taz     
    pla     
    tza     
    rtn #0
    .func_flags stack_call
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _print_ctrl_b
    .var _fp = 0
    ; frame: 1 bytes
    lda     #$00
    pha     
    .local _l_reg = 0
; [main.c:97]     vic_ctrl_b reg;
; [main.c:98]     reg = *VICIV_CTRL_B;
    ldax _VICIV_CTRL_B
    stax $03
    ptrderef $03
    sta.sp _l_reg
; [main.c:100]     printf("vic ctrl b ($d054):\n");
    ldax #STR3
    push    .ax
    .var _fp = _fp + 2
    jsr _printf
    taz     
    pla     
    pla     
    tza     
    .var _fp = _fp - 2
; [main.c:101]     printf("  fclksel=%d vfast=%d\n",
; [main.c:102]            reg.fclksel, reg.vfast);
    lda.sp _l_reg
    ldx     #$00
    bfext #2, #1
    push    .ax
    .var _fp = _fp + 2
    lda.sp _l_reg
    ldx     #$00
    bfext #0, #2
    push    .ax
    .var _fp = _fp + 2
    ldax #STR4
    push    .ax
    .var _fp = _fp + 2
    jsr _printf
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 6
; [main.c:103]     printf("  alpha=%d rst_emu=%d\n",
; [main.c:104]            reg.alpha, reg.rst_emu);
    lda.sp _l_reg
    ldx     #$00
    bfext #6, #1
    push    .ax
    .var _fp = _fp + 2
    lda.sp _l_reg
    ldx     #$00
    bfext #7, #1
    push    .ax
    .var _fp = _fp + 2
    ldax #STR5
    push    .ax
    .var _fp = _fp + 2
    jsr _printf
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 6
    taz     
    pla     
    tza     
    rtn #0
    .func_flags stack_call
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _main
    .var _fp = 0
; [main.c:108]     unlock_mega65_io();
    jsr _unlock_mega65_io
; [main.c:110]     puts("bitfield register demo");
    ldax #STR6
    push    .ax
    .var _fp = _fp + 2
    jsr _puts
    taz     
    pla     
    pla     
    tza     
    .var _fp = _fp - 2
; [main.c:111]     puts("----------------------");
    ldax #STR7
    push    .ax
    .var _fp = _fp + 2
    jsr _puts
    taz     
    pla     
    pla     
    tza     
    .var _fp = _fp - 2
; [main.c:114]     print_ctrl_a();
    jsr _print_ctrl_a
; [main.c:115]     print_ctrl_b();
    jsr _print_ctrl_b
; [main.c:118]     printf("\nsetting 40mhz...\n");
    ldax #STR8
    push    .ax
    .var _fp = _fp + 2
    jsr _printf
    taz     
    pla     
    pla     
    tza     
    .var _fp = _fp - 2
; [main.c:119]     VICIV_CTRL_B->fclksel = 3;    
    ldax #$0003
    stax $03
    ldax _VICIV_CTRL_B
    stax $05
    ldax $03
    bfins.ind $05, #0, #2
; [main.c:121]     print_ctrl_b();
    jsr _print_ctrl_b
; [main.c:124]     printf("\nenabling sprites 0,2...\n");
    ldax #STR9
    push    .ax
    .var _fp = _fp + 2
    jsr _printf
    taz     
    pla     
    pla     
    tza     
    .var _fp = _fp - 2
; [main.c:125]     SPR_ENABLE->spr0 = 1;
    ldax #$0001
    stax $03
    ldax _SPR_ENABLE
    stax $05
    ldax $03
    bfins.ind $05, #0, #1
; [main.c:126]     SPR_ENABLE->spr2 = 1;
    ldax #$0001
    stax $03
    ldax _SPR_ENABLE
    stax $05
    ldax $03
    bfins.ind $05, #2, #1
; [main.c:127]     printf("spr enable: $%x\n", *(unsigned char *)0xD015);
    ldax #$D015
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    push    .ax
    .var _fp = _fp + 2
    ldax #STR10
    push    .ax
    .var _fp = _fp + 2
    jsr _printf
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 4
; [main.c:130]     printf("\nwriting styled chars...\n");
    ldax #STR11
    push    .ax
    .var _fp = _fp + 2
    jsr _printf
    taz     
    pla     
    pla     
    tza     
    .var _fp = _fp - 2
; [main.c:131]     SCREEN[0].ch = 1;          
    ldax #$0001
    stax $03
    ldax _SCREEN
    stax $05
    zero a, x
    asl     a
    pha     
    txa     
    rol     a
    tax     
    pla     
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:132]     SCREEN[0].color = 2;       
    ldax #$0002
    stax $03
    ldax _SCREEN
    stax $05
    zero a, x
    asl     a
    pha     
    txa     
    rol     a
    tax     
    pla     
    add.16 .ax, $05
    add.16  .ax, #$0001
    stax $05
    ldax $03
    bfins.ind $05, #0, #4
; [main.c:133]     SCREEN[0].bold = 1;
    ldax #$0001
    stax $03
    ldax _SCREEN
    stax $05
    zero a, x
    asl     a
    pha     
    txa     
    rol     a
    tax     
    pla     
    add.16 .ax, $05
    add.16  .ax, #$0001
    stax $05
    ldax $03
    bfins.ind $05, #6, #1
; [main.c:134]     SCREEN[0].rvs = 1;
    ldax #$0001
    stax $03
    ldax _SCREEN
    stax $05
    zero a, x
    asl     a
    pha     
    txa     
    rol     a
    tax     
    pla     
    add.16 .ax, $05
    add.16  .ax, #$0001
    stax $05
    ldax $03
    bfins.ind $05, #7, #1
; [main.c:136]     SCREEN[1].ch = 2;          
    ldax #$0002
    stax $03
    ldax _SCREEN
    stax $05
    ldax #$0001
    asl     a
    pha     
    txa     
    rol     a
    tax     
    pla     
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:137]     SCREEN[1].color = 5;       
    ldax #$0005
    stax $03
    ldax _SCREEN
    stax $05
    ldax #$0001
    asl     a
    pha     
    txa     
    rol     a
    tax     
    pla     
    add.16 .ax, $05
    add.16  .ax, #$0001
    stax $05
    ldax $03
    bfins.ind $05, #0, #4
; [main.c:138]     SCREEN[1].under = 1;
    ldax #$0001
    stax $03
    ldax _SCREEN
    stax $05
    ldax #$0001
    asl     a
    pha     
    txa     
    rol     a
    tax     
    pla     
    add.16 .ax, $05
    add.16  .ax, #$0001
    stax $05
    ldax $03
    bfins.ind $05, #5, #1
; [main.c:140]     puts("\ndone.");
    ldax #STR12
    push    .ax
    .var _fp = _fp + 2
    jsr _puts
    taz     
    pla     
    pla     
    tza     
    .var _fp = _fp - 2
; [main.c:141]     return 0;
    zero a, x
    rtn #0
    .func_flags stack_call
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.global _VICIV_CTRL_A
.global _VICIV_CTRL_B
.global _SPR_ENABLE
.global _SCREEN

.data
; Data Section
_VICIV_CTRL_A:
    .word $D031
_VICIV_CTRL_B:
    .word $D054
_SPR_ENABLE:
    .word $D015
_SCREEN:
    .word $0800

.data
STR12:
    .text "
done."
    .byte 0
STR9:
    .text "
enabling sprites 0,2...
"
    .byte 0
STR8:
    .text "
setting 40mhz...
"
    .byte 0
STR11:
    .text "
writing styled chars...
"
    .byte 0
STR5:
    .text "  alpha=%d rst_emu=%d
"
    .byte 0
STR2:
    .text "  bpm=%d v400=%d chr16=%d
"
    .byte 0
STR4:
    .text "  fclksel=%d vfast=%d
"
    .byte 0
STR1:
    .text "  h640=%d fast=%d attr=%d
"
    .byte 0
STR7:
    .text "----------------------"
    .byte 0
STR6:
    .text "bitfield register demo"
    .byte 0
STR10:
    .text "spr enable: $%x
"
    .byte 0
STR0:
    .text "vic ctrl a ($d031):
"
    .byte 0
STR3:
    .text "vic ctrl b ($d054):
"
    .byte 0
