; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _apply_fade
.extern _save_palette
.extern _unlock_viciv
.global _main

.code
proc _main
    .var _fp = 0
    ; frame: 1 bytes locals + 0 bytes caller-save
    lda     #$00
    pha     
    .local _l_level = 0
; [palette_fade.c:17]     unlock_viciv();
    jsr _unlock_viciv
; [palette_fade.c:20]     save_palette();
    jsr _save_palette
; [palette_fade.c:23]     while (1) {
L0:
; [palette_fade.c:24]         unsigned char level;
; [palette_fade.c:27]         for (level = 0; level < 255; level++) {
    lda     #$00
    sta.sp _l_level
L2:
    lda.sp _l_level
    ldx     #$00
    stax $03
    ldax #$00FF
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcs @L5
    lda     #$01
    bra     *+4
@L5:
    lda     #$00
@L6:
    ldx     #$00
    cmp #$00
    beq L4
; [palette_fade.c:28]             apply_fade(level);
    lda.sp _l_level
    ldx     #$00
    sta $03
    jsr _apply_fade
L3:
    inc _l_level, s
    bra L2
L4:
; [palette_fade.c:30]         apply_fade(255);
    ldax #$00FF
    sta $03
    jsr _apply_fade
; [palette_fade.c:33]         for (level = 255; level > 0; level--) {
    lda     #$FF
    sta.sp _l_level
L7:
    lda.sp _l_level
    ldx     #$00
    stax $03
    zero a, x
    stax $05
    ldax $03
    cmp.16 .ax, $05
    beq @L10
    bcc @L10
    lda     #$01
    bra     *+4
@L10:
    lda     #$00
@L11:
    ldx     #$00
    cmp #$00
    beq L9
; [palette_fade.c:34]             apply_fade(level);
    lda.sp _l_level
    ldx     #$00
    sta $03
    jsr _apply_fade
L8:
    dec _l_level, s
    bra L7
L9:
; [palette_fade.c:36]         apply_fade(0);
    zero a, x
    sta $03
    jsr _apply_fade
    bra L0
L1:
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc


.data
; Data Section

.data
