; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _itoa
.extern _strcmp
.global _main

; [test_itoa.c:33] char buf[20];
.code
proc _main
    .var _fp = 0
; [test_itoa.c:37]     itoa(0, buf, 10);
    zero a, x
    push    .ax
    ptrstack _buf
    push    a
    ldax #$000A
    push    .ax
    jsr _itoa
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_itoa.c:38]     if (strcmp(buf, "0") != 0) return 1;
    ptrstack _buf
    push    a
    ldax #<STR0
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L2
    lda     #$01
    bra     *+4
@L2:
    lda     #$00
@L3:
    ldx     #$00
    cmp #$00
    beq L0
    ldax #$0001
    rtn #0
L0:
; [test_itoa.c:40]     itoa(1, buf, 10);
    ldax #$0001
    push    .ax
    ptrstack _buf
    push    a
    ldax #$000A
    push    .ax
    jsr _itoa
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_itoa.c:41]     if (strcmp(buf, "1") != 0) return 2;
    ptrstack _buf
    push    a
    ldax #<STR1
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L6
    lda     #$01
    bra     *+4
@L6:
    lda     #$00
@L7:
    ldx     #$00
    cmp #$00
    beq L4
    ldax #$0002
    rtn #0
L4:
; [test_itoa.c:43]     itoa(123, buf, 10);
    ldax #$007B
    push    .ax
    ptrstack _buf
    push    a
    ldax #$000A
    push    .ax
    jsr _itoa
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_itoa.c:44]     if (strcmp(buf, "123") != 0) return 3;
    ptrstack _buf
    push    a
    ldax #<STR2
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L10
    lda     #$01
    bra     *+4
@L10:
    lda     #$00
@L11:
    ldx     #$00
    cmp #$00
    beq L8
    ldax #$0003
    rtn #0
L8:
; [test_itoa.c:46]     itoa(65535, buf, 10);
    ldax #$FFFF
    push    .ax
    ptrstack _buf
    push    a
    ldax #$000A
    push    .ax
    jsr _itoa
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_itoa.c:47]     if (strcmp(buf, "65535") != 0) return 4;
    ptrstack _buf
    push    a
    ldax #<STR3
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L14
    lda     #$01
    bra     *+4
@L14:
    lda     #$00
@L15:
    ldx     #$00
    cmp #$00
    beq L12
    ldax #$0004
    rtn #0
L12:
; [test_itoa.c:50]     itoa(255, buf, 16);
    ldax #$00FF
    push    .ax
    ptrstack _buf
    push    a
    ldax #$0010
    push    .ax
    jsr _itoa
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_itoa.c:51]     if (strcmp(buf, "ff") != 0) return 5;
    ptrstack _buf
    push    a
    ldax #<STR4
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L18
    lda     #$01
    bra     *+4
@L18:
    lda     #$00
@L19:
    ldx     #$00
    cmp #$00
    beq L16
    ldax #$0005
    rtn #0
L16:
; [test_itoa.c:53]     itoa(4096, buf, 16);
    ldax #$1000
    push    .ax
    ptrstack _buf
    push    a
    ldax #$0010
    push    .ax
    jsr _itoa
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_itoa.c:54]     if (strcmp(buf, "1000") != 0) return 6;
    ptrstack _buf
    push    a
    ldax #<STR5
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L22
    lda     #$01
    bra     *+4
@L22:
    lda     #$00
@L23:
    ldx     #$00
    cmp #$00
    beq L20
    ldax #$0006
    rtn #0
L20:
; [test_itoa.c:57]     itoa(10, buf, 2);
    ldax #$000A
    push    .ax
    ptrstack _buf
    push    a
    ldax #$0002
    push    .ax
    jsr _itoa
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_itoa.c:58]     if (strcmp(buf, "1010") != 0) return 7;
    ptrstack _buf
    push    a
    ldax #<STR6
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L26
    lda     #$01
    bra     *+4
@L26:
    lda     #$00
@L27:
    ldx     #$00
    cmp #$00
    beq L24
    ldax #$0007
    rtn #0
L24:
; [test_itoa.c:61]     itoa(7, buf, 8);
    ldax #$0007
    push    .ax
    ptrstack _buf
    push    a
    ldax #$0008
    push    .ax
    jsr _itoa
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
; [test_itoa.c:62]     if (strcmp(buf, "7") != 0) return 8;
    ptrstack _buf
    push    a
    ldax #<STR7
    push    .ax
    jsr _strcmp
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L30
    lda     #$01
    bra     *+4
@L30:
    lda     #$00
@L31:
    ldx     #$00
    cmp #$00
    beq L28
    ldax #$0008
    rtn #0
L28:
; [test_itoa.c:64]     return 0;
    zero a, x
    rtn #0
    endproc

.global _buf

.code
_init_bss:
    rts

.data
; Data Section

.bss
; BSS Section
__bss_start:
_buf:
    .res 20
__bss_end:

.data
STR0:
    .text "0"
    .byte 0
STR1:
    .text "1"
    .byte 0
STR5:
    .text "1000"
    .byte 0
STR6:
    .text "1010"
    .byte 0
STR2:
    .text "123"
    .byte 0
STR3:
    .text "65535"
    .byte 0
STR7:
    .text "7"
    .byte 0
STR4:
    .text "ff"
    .byte 0
