; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _atoi
.global _main

.code
proc _main
    .var _fp = 0
; [test_atoi.c:16]     if (atoi("0") != 0) return 1;
    ldax #<STR0
    push    .ax
    jsr _atoi
    taz     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L2
    lda     #$01
    bra     *+4
@L2:
    lda     #$00
@L3:
    ldx     #$00
    cmp #$00
    beq L0
    ldax #$0001
    rtn #0
L0:
; [test_atoi.c:17]     if (atoi("1") != 1) return 2;
    ldax #<STR1
    push    .ax
    jsr _atoi
    taz     
    pla     
    pla     
    tza     
    stax $02
    ldax #$0001
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L6
    lda     #$01
    bra     *+4
@L6:
    lda     #$00
@L7:
    ldx     #$00
    cmp #$00
    beq L4
    ldax #$0002
    rtn #0
L4:
; [test_atoi.c:18]     if (atoi("123") != 123) return 3;
    ldax #<STR2
    push    .ax
    jsr _atoi
    taz     
    pla     
    pla     
    tza     
    stax $02
    ldax #$007B
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L10
    lda     #$01
    bra     *+4
@L10:
    lda     #$00
@L11:
    ldx     #$00
    cmp #$00
    beq L8
    ldax #$0003
    rtn #0
L8:
; [test_atoi.c:19]     if (atoi("65535") != 65535) return 4;
    ldax #<STR3
    push    .ax
    jsr _atoi
    taz     
    pla     
    pla     
    tza     
    stax $02
    ldax #$FFFF
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L14
    lda     #$01
    bra     *+4
@L14:
    lda     #$00
@L15:
    ldx     #$00
    cmp #$00
    beq L12
    ldax #$0004
    rtn #0
L12:
; [test_atoi.c:22]     if (atoi("  42") != 42) return 5;
    ldax #<STR4
    push    .ax
    jsr _atoi
    taz     
    pla     
    pla     
    tza     
    stax $02
    ldax #$002A
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L18
    lda     #$01
    bra     *+4
@L18:
    lda     #$00
@L19:
    ldx     #$00
    cmp #$00
    beq L16
    ldax #$0005
    rtn #0
L16:
; [test_atoi.c:25]     if (atoi("+7") != 7) return 6;
    ldax #<STR5
    push    .ax
    jsr _atoi
    taz     
    pla     
    pla     
    tza     
    stax $02
    ldax #$0007
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L22
    lda     #$01
    bra     *+4
@L22:
    lda     #$00
@L23:
    ldx     #$00
    cmp #$00
    beq L20
    ldax #$0006
    rtn #0
L20:
; [test_atoi.c:28]     if (atoi("") != 0) return 7;
    ldax #<STR6
    push    .ax
    jsr _atoi
    taz     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L26
    lda     #$01
    bra     *+4
@L26:
    lda     #$00
@L27:
    ldx     #$00
    cmp #$00
    beq L24
    ldax #$0007
    rtn #0
L24:
; [test_atoi.c:29]     if (atoi("abc") != 0) return 8;
    ldax #<STR7
    push    .ax
    jsr _atoi
    taz     
    pla     
    pla     
    tza     
    stax $02
    zero a, x
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L30
    lda     #$01
    bra     *+4
@L30:
    lda     #$00
@L31:
    ldx     #$00
    cmp #$00
    beq L28
    ldax #$0008
    rtn #0
L28:
; [test_atoi.c:32]     if (atoi("99xyz") != 99) return 9;
    ldax #<STR8
    push    .ax
    jsr _atoi
    taz     
    pla     
    pla     
    tza     
    stax $02
    ldax #$0063
    stax $04
    ldax $02
    cmp.16 .ax, $04
    beq @L34
    lda     #$01
    bra     *+4
@L34:
    lda     #$00
@L35:
    ldx     #$00
    cmp #$00
    beq L32
    ldax #$0009
    rtn #0
L32:
; [test_atoi.c:34]     return 0;
    zero a, x
    rtn #0
    endproc


.code
_init_bss:
    rts

.data
; Data Section

.data
STR6:
    .text ""
    .byte 0
STR4:
    .text "  42"
    .byte 0
STR5:
    .text "+7"
    .byte 0
STR0:
    .text "0"
    .byte 0
STR1:
    .text "1"
    .byte 0
STR2:
    .text "123"
    .byte 0
STR3:
    .text "65535"
    .byte 0
STR8:
    .text "99xyz"
    .byte 0
STR7:
    .text "abc"
    .byte 0
