; Generated by cc45
.segmentOrder code, data, bss
.code
.extern _memcpy
.extern _memset
.global _main
.extern __sp_base

; [main.c:47] char grid[25][40];
; [main.c:48] char next[25][40];
; [main.c:51] char *screen = 0x0400;
; [main.c:53] char *color = 0xD800;
.code
proc _clear_grid
    .var _fp = 0
; [main.c:56]     memset(grid, 0, 40 * 25);
    ptrstack _grid
    push    .ax
    .var _fp = _fp + 2
    zero a, x
    push    .ax
    .var _fp = _fp + 2
    ldax #$03E8
    push    .ax
    .var _fp = _fp + 2
    jsr _memset
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 6
; [main.c:57]     memset(next, 0, 40 * 25);
    ptrstack _next
    push    .ax
    .var _fp = _fp + 2
    zero a, x
    push    .ax
    .var _fp = _fp + 2
    ldax #$03E8
    push    .ax
    .var _fp = _fp + 2
    jsr _memset
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 6
    rtn #0
    .func_flags stack_call
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _count_neighbors, W#_p_row, W#_p_col
    .var _fp = 0
    ; frame: 10 bytes
    phw     #$0000
    phw     #$0000
    phw     #$0000
    phw     #$0000
    phw     #$0000
    .local _l_count = 0
    .local _l_r = 2
    .local _l_c = 4
    .local _l_nr = 6
    .local _l_nc = 8
    .var _p_col = 12
    .var _p_row = 14
; [main.c:62]     int count;
; [main.c:63]     int r;
; [main.c:64]     int c;
; [main.c:65]     int nr;
; [main.c:66]     int nc;
; [main.c:68]     count = 0;
    stw.sp #$0000, _l_count
; [main.c:69]     for (r = -1; r <= 1; r++) {
    stw.sp #$FFFF, _l_r
L0:
    ldax _l_r, s
    stax $03
    ldax #$0001
    stax $05
    ldax $03
    cmp.16 .ax, $05
    beq @L5
    bcs @L3
@L5:
    lda     #$01
    bra     *+4
@L3:
    lda     #$00
@L4:
    ldx     #$00
    cmp #$00
    beq L2
; [main.c:70]         for (c = -1; c <= 1; c++) {
    stw.sp #$FFFF, _l_c
L6:
    ldax _l_c, s
    stax $03
    ldax #$0001
    stax $05
    ldax $03
    cmp.16 .ax, $05
    beq @L11
    bcs @L9
@L11:
    lda     #$01
    bra     *+4
@L9:
    lda     #$00
@L10:
    ldx     #$00
    cmp #$00
    beq L8
; [main.c:71]             if (r == 0 && c == 0) continue;
    ldax _l_r, s
    stax $03
    zero a, x
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bne @L14
    lda     #$01
    bra     *+4
@L14:
    lda     #$00
@L15:
    ldx     #$00
    cmp #$00
    beq L12
    ldax _l_c, s
    stax $03
    zero a, x
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bne @L16
    lda     #$01
    bra     *+4
@L16:
    lda     #$00
@L17:
    ldx     #$00
    cmp #$00
    beq L12
    bra L7
L12:
; [main.c:72]             nr = row + r;
    ldax _p_row, s
    stax $03
    ldax _l_r, s
    add.16 .ax, $03
    stax _l_nr, s
; [main.c:73]             nc = col + c;
    ldax _p_col, s
    stax $03
    ldax _l_c, s
    add.16 .ax, $03
    stax _l_nc, s
; [main.c:75]             if (nr < 0) nr = 25 - 1;
    ldax _l_nr, s
    stax $03
    zero a, x
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcs @L20
    lda     #$01
    bra     *+4
@L20:
    lda     #$00
@L21:
    ldx     #$00
    cmp #$00
    beq L18
    stw.sp #$0018, _l_nr
L18:
; [main.c:76]             if (nr >= 25) nr = 0;
    ldax _l_nr, s
    stax $03
    ldax #$0019
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcc @L24
    lda     #$01
    bra     *+4
@L24:
    lda     #$00
@L25:
    ldx     #$00
    cmp #$00
    beq L22
    stw.sp #$0000, _l_nr
L22:
; [main.c:77]             if (nc < 0) nc = 40 - 1;
    ldax _l_nc, s
    stax $03
    zero a, x
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcs @L28
    lda     #$01
    bra     *+4
@L28:
    lda     #$00
@L29:
    ldx     #$00
    cmp #$00
    beq L26
    stw.sp #$0027, _l_nc
L26:
; [main.c:78]             if (nc >= 40) nc = 0;
    ldax _l_nc, s
    stax $03
    ldax #$0028
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcc @L32
    lda     #$01
    bra     *+4
@L32:
    lda     #$00
@L33:
    ldx     #$00
    cmp #$00
    beq L30
    stw.sp #$0000, _l_nc
L30:
; [main.c:79]             if (grid[nr][nc]) count++;
    ptrstack _grid
    stax $03
    ldax _l_nr, s
    mul.16 .ax, #$0028
    add.16 .ax, $03
    stax $03
    ldax _l_nc, s
    add.16 .ax, $03
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    cmp #$00
    beq L34
    inw _l_count, s
L34:
L7:
    inw _l_c, s
    bra L6
L8:
L1:
    inw _l_r, s
    bra L0
L2:
; [main.c:82]     return count;
    ldax _l_count, s
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _step
    .var _fp = 0
    ; frame: 6 bytes
    phw     #$0000
    phw     #$0000
    phw     #$0000
    .local _l_r = 0
    .local _l_c = 2
    .local _l_n = 4
; [main.c:86]     int r;
; [main.c:87]     int c;
; [main.c:88]     int n;
; [main.c:90]     for (r = 0; r < 25; r++) {
    stw.sp #$0000, _l_r
L36:
    ldax _l_r, s
    stax $03
    ldax #$0019
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcs @L39
    lda     #$01
    bra     *+4
@L39:
    lda     #$00
@L40:
    ldx     #$00
    cmp #$00
    beq L38
; [main.c:91]         for (c = 0; c < 40; c++) {
    stw.sp #$0000, _l_c
L41:
    ldax _l_c, s
    stax $03
    ldax #$0028
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcs @L44
    lda     #$01
    bra     *+4
@L44:
    lda     #$00
@L45:
    ldx     #$00
    cmp #$00
    beq L43
; [main.c:92]             n = count_neighbors(r, c);
    ldax _l_r, s
    push    .ax
    .var _fp = _fp + 2
    ldax _l_c, s
    push    .ax
    .var _fp = _fp + 2
    jsr _count_neighbors
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 4
    stax _l_n, s
; [main.c:93]             if (grid[r][c]) {
    ptrstack _grid
    stax $03
    ldax _l_r, s
    mul.16 .ax, #$0028
    add.16 .ax, $03
    stax $03
    ldax _l_c, s
    add.16 .ax, $03
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    cmp #$00
    beq L46
; [main.c:95]                 if (n == 2 || n == 3)
    ldax _l_n, s
    stax $03
    ldax #$0002
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bne @L51
    lda     #$01
    bra     *+4
@L51:
    lda     #$00
@L52:
    ldx     #$00
    cmp #$00
    bne @L50
    ldax _l_n, s
    stax $03
    ldax #$0003
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bne @L53
    lda     #$01
    bra     *+4
@L53:
    lda     #$00
@L54:
    ldx     #$00
    cmp #$00
    beq L48
@L50:
; [main.c:96]                     next[r][c] = 1;
    ldax #$0001
    stax $03
    ptrstack _next
    stax $05
    ldax _l_r, s
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _l_c, s
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
    bra L49
L48:
; [main.c:98]                     next[r][c] = 0;
    zero a, x
    stax $03
    ptrstack _next
    stax $05
    ldax _l_r, s
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _l_c, s
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
L49:
    bra L47
L46:
; [main.c:101]                 if (n == 3)
    ldax _l_n, s
    stax $03
    ldax #$0003
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bne @L57
    lda     #$01
    bra     *+4
@L57:
    lda     #$00
@L58:
    ldx     #$00
    cmp #$00
    beq L55
; [main.c:102]                     next[r][c] = 1;
    ldax #$0001
    stax $03
    ptrstack _next
    stax $05
    ldax _l_r, s
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _l_c, s
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
    bra L56
L55:
; [main.c:104]                     next[r][c] = 0;
    zero a, x
    stax $03
    ptrstack _next
    stax $05
    ldax _l_r, s
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _l_c, s
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
L56:
L47:
L42:
    inw _l_c, s
    bra L41
L43:
L37:
    inw _l_r, s
    bra L36
L38:
; [main.c:110]     memcpy(grid, next, 40 * 25);
    ptrstack _grid
    push    .ax
    .var _fp = _fp + 2
    ptrstack _next
    push    .ax
    .var _fp = _fp + 2
    ldax #$03E8
    push    .ax
    .var _fp = _fp + 2
    jsr _memcpy
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 6
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    rtn #0
    .func_flags stack_call
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _draw
    .var _fp = 0
    ; frame: 6 bytes
    phw     #$0000
    phw     #$0000
    phw     #$0000
    .local _l_r = 0
    .local _l_c = 2
    .local _l_offset = 4
; [main.c:114]     int r;
; [main.c:115]     int c;
; [main.c:116]     int offset;
; [main.c:118]     for (r = 0; r < 25; r++) {
    stw.sp #$0000, _l_r
L59:
    ldax _l_r, s
    stax $03
    ldax #$0019
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcs @L62
    lda     #$01
    bra     *+4
@L62:
    lda     #$00
@L63:
    ldx     #$00
    cmp #$00
    beq L61
; [main.c:119]         for (c = 0; c < 40; c++) {
    stw.sp #$0000, _l_c
L64:
    ldax _l_c, s
    stax $03
    ldax #$0028
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcs @L67
    lda     #$01
    bra     *+4
@L67:
    lda     #$00
@L68:
    ldx     #$00
    cmp #$00
    beq L66
; [main.c:120]             offset = r * 40 + c;
    ldax _l_r, s
    stax $03
    ldax #$0028
    mul.16 .ax, $03
    stax $03
    ldax _l_c, s
    add.16 .ax, $03
    stax _l_offset, s
; [main.c:121]             if (grid[r][c])
    ptrstack _grid
    stax $03
    ldax _l_r, s
    mul.16 .ax, #$0028
    add.16 .ax, $03
    stax $03
    ldax _l_c, s
    add.16 .ax, $03
    stax $03
    ldy     #$00
    lda     ($03),y
    ldx     #$00
    cmp #$00
    beq L69
; [main.c:122]                 screen[offset] = 0x2A;
    ldax #$002A
    stax $03
    ldax _screen
    stax $05
    ldax _l_offset, s
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
    bra L70
L69:
; [main.c:124]                 screen[offset] = 0x20;
    ldax #$0020
    stax $03
    ldax _screen
    stax $05
    ldax _l_offset, s
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
L70:
L65:
    inw _l_c, s
    bra L64
L66:
L60:
    inw _l_r, s
    bra L59
L61:
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _delay
    .var _fp = 0
    ; frame: 2 bytes
    phw     #$0000
    .local _l_i = 0
; [main.c:130]     int i;
; [main.c:131]     for (i = 0; i < 2000; i++) {
    stw.sp #$0000, _l_i
L71:
    ldax _l_i, s
    stax $03
    ldax #$07D0
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcs @L74
    lda     #$01
    bra     *+4
@L74:
    lda     #$00
@L75:
    ldx     #$00
    cmp #$00
    beq L73
L72:
    inw _l_i, s
    bra L71
L73:
    taz     
    pla     
    pla     
    tza     
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _seed_r_pentomino, W#_p_row, W#_p_col
    .var _fp = 0
    .var _p_col = 2
    .var _p_row = 4
; [main.c:138]     grid[row][col + 1]     = 1;
    ldax #$0001
    stax $03
    ptrstack _grid
    stax $05
    ldax _p_row, s
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _p_col, s
    inc     a
    bne     *+3
    inx
@L76:
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:139]     grid[row][col + 2]     = 1;
    ldax #$0001
    stax $03
    ptrstack _grid
    stax $05
    ldax _p_row, s
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _p_col, s
    stax $07
    ldax #$0002
    add.16 .ax, $07
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:140]     grid[row + 1][col]     = 1;
    ldax #$0001
    stax $03
    ptrstack _grid
    stax $05
    ldax _p_row, s
    inc     a
    bne     *+3
    inx
@L77:
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _p_col, s
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:141]     grid[row + 1][col + 1] = 1;
    ldax #$0001
    stax $03
    ptrstack _grid
    stax $05
    ldax _p_row, s
    inc     a
    bne     *+3
    inx
@L78:
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _p_col, s
    inc     a
    bne     *+3
    inx
@L79:
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:142]     grid[row + 2][col + 1] = 1;
    ldax #$0001
    stax $03
    ptrstack _grid
    stax $05
    ldax _p_row, s
    stax $07
    ldax #$0002
    add.16 .ax, $07
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _p_col, s
    inc     a
    bne     *+3
    inx
@L80:
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _seed_glider, W#_p_row, W#_p_col
    .var _fp = 0
    .var _p_col = 2
    .var _p_row = 4
; [main.c:147]     grid[row][col + 1]     = 1;
    ldax #$0001
    stax $03
    ptrstack _grid
    stax $05
    ldax _p_row, s
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _p_col, s
    inc     a
    bne     *+3
    inx
@L81:
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:148]     grid[row + 1][col + 2] = 1;
    ldax #$0001
    stax $03
    ptrstack _grid
    stax $05
    ldax _p_row, s
    inc     a
    bne     *+3
    inx
@L82:
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _p_col, s
    stax $07
    ldax #$0002
    add.16 .ax, $07
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:149]     grid[row + 2][col]     = 1;
    ldax #$0001
    stax $03
    ptrstack _grid
    stax $05
    ldax _p_row, s
    stax $07
    ldax #$0002
    add.16 .ax, $07
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _p_col, s
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:150]     grid[row + 2][col + 1] = 1;
    ldax #$0001
    stax $03
    ptrstack _grid
    stax $05
    ldax _p_row, s
    stax $07
    ldax #$0002
    add.16 .ax, $07
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _p_col, s
    inc     a
    bne     *+3
    inx
@L83:
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
; [main.c:151]     grid[row + 2][col + 2] = 1;
    ldax #$0001
    stax $03
    ptrstack _grid
    stax $05
    ldax _p_row, s
    stax $07
    ldax #$0002
    add.16 .ax, $07
    mul.16 .ax, #$0028
    add.16 .ax, $05
    stax $05
    ldax _p_col, s
    stax $07
    ldax #$0002
    add.16 .ax, $07
    add.16 .ax, $05
    stax $05
    ldax $03
    ldy     #$00
    sta     ($05),y
    rtn #0
    .func_flags stack_call, leaf
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.code
proc _main
    .var _fp = 0
    ; frame: 2 bytes
    phw     #$0000
    .local _l_gen = 0
; [main.c:155]     int gen;
; [main.c:157]     clear_grid();
    jsr _clear_grid
; [main.c:160]     seed_r_pentomino(10, 18);
    ldax #$000A
    push    .ax
    .var _fp = _fp + 2
    ldax #$0012
    push    .ax
    .var _fp = _fp + 2
    jsr _seed_r_pentomino
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 4
; [main.c:161]     seed_glider(2, 2);
    ldax #$0002
    push    .ax
    .var _fp = _fp + 2
    ldax #$0002
    push    .ax
    .var _fp = _fp + 2
    jsr _seed_glider
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 4
; [main.c:162]     seed_glider(3, 30);
    ldax #$0003
    push    .ax
    .var _fp = _fp + 2
    ldax #$001E
    push    .ax
    .var _fp = _fp + 2
    jsr _seed_glider
    taz     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 4
; [main.c:165]     memset(color, (char)5, 40 * 25);
    ldax _color
    push    .ax
    .var _fp = _fp + 2
    ldax #$0005
    push    .ax
    .var _fp = _fp + 2
    ldax #$03E8
    push    .ax
    .var _fp = _fp + 2
    jsr _memset
    taz     
    pla     
    pla     
    pla     
    pla     
    pla     
    pla     
    tza     
    .var _fp = _fp - 6
; [main.c:167]     for (gen = 0; gen < 500; gen++) {
    stw.sp #$0000, _l_gen
L84:
    ldax _l_gen, s
    stax $03
    ldax #$01F4
    stax $05
    ldax $03
    cmp.16 .ax, $05
    bcs @L87
    lda     #$01
    bra     *+4
@L87:
    lda     #$00
@L88:
    ldx     #$00
    cmp #$00
    beq L86
; [main.c:168]         draw();
    jsr _draw
; [main.c:169]         delay();
    jsr _delay
; [main.c:170]         step();
    jsr _step
L85:
    inw _l_gen, s
    bra L84
L86:
; [main.c:173]     return 0;
    zero a, x
    taz     
    pla     
    pla     
    tza     
    rtn #0
    .func_flags stack_call
    .reg_clobbers A, X, Y, Z
    .flag_clobbers C, N, Z, V
    endproc

.global _grid
.global _next
.global _screen
.global _color

.data
; Data Section
_screen:
    .word $0400
_color:
    .word $D800

.bss
; BSS Section
.global _grid
_grid:
    .res 1000
.global _next
_next:
    .res 1000

.data
